[Carto numQ-3] Frais à charge - Liste déroulante
betagouv/dora-front pull request #116
Opened 2022-10-03 16:34 UTC by AlexandreCantin

=> https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=8bd2b92e04064c84b1e475e8b65c88e2&pm=s

2022-10-04 10:43 UTC, cedricr requested changes
Le merge avec main est à vérifier...

2022-10-04 10:43 UTC, cedricr commented on src/lib/components/services/body/service-key-informations.svelte
> +  {#if service.feeCondition && hasFee(service.feeCondition)}
ça m'etonne un peu que tu testes service.feeCondition et pas l.40
J'imagine que c'est à cause du getLabelFromValue? Mais on risque d'avoir une inconsistence entre les deux endroits.

2022-10-04 10:43 UTC, cedricr commented on src/lib/components/services/model-body.svelte
> +        {#if service.feeCondition && hasFee(service.feeCondition)}
même remarque que sur les services

2022-10-04 10:43 UTC, cedricr commented on src/lib/schemas/service.js
> +        valid: data.feeCondition === "gratuit",
marche pas, ce n'est valide que si c'est gratuit, alors que tu veux gratuit ou non vide

```suggestion
        valid: data.feeCondition === "gratuit" || value.length,
```

2022-10-04 10:43 UTC, cedricr commented on src/lib/services.js
> +  if (!servicesOptions) {
attention, tu cours-circuite les eventuels changements de valeur dans le parametre 'model'

Tu pourrais à la place mettre un cache un 'baseServiceOption' qui ne fait la requete qu'une fois, et renvoyer le resultat modifié.

2022-10-04 13:45 UTC, AlexandreCantin commented on src/lib/schemas/service.js
> +        valid: data.feeCondition === "gratuit",
En effet... en effet... :/

2022-10-04 14:35 UTC, AlexandreCantin commented on src/lib/components/services/body/service-key-informations.svelte
> +  {#if service.feeCondition && hasFee(service.feeCondition)}
hum... j'ai un dliemme sur ce point...

À la base, je voulais juste que `hasFee` vérifie si le service pouvait engendrer des frais (et pas forcément la présence du champ). Du coup, ma fonction fait deux choses et son nom prête à confusion - voire est trompeur - je vais la renommer

2022-10-04 14:55 UTC, AlexandreCantin commented on src/lib/components/services/body/service-key-informations.svelte
> +  {#if service.feeCondition && hasFee(service.feeCondition)}
J'ai opté sur `isNotFreeService` plutôt que `hasFee`
Le nom n'est pas le plus satisfaisant - mais il est moins confusant que `hasFee`

2022-10-04 14:56 UTC, AlexandreCantin commented on src/lib/services.js
> +  if (!servicesOptions) {
Du coup, j'ai fait le `baseServiceOption`

2022-10-05 07:52 UTC, cedricr requested changes

2022-10-05 07:52 UTC, cedricr commented on src/routes/recherche.svelte
> +        services: await getResults({
`services` est déjà calculé au-dessus (sans doute toujours le même pb de merge)

2022-10-05 07:52 UTC, cedricr commented on src/routes/recherche.svelte
> +  if (browser) {
ça a été deplacé ça, ça n'a plus lieu d'être ici (tu le vois bien dans le diff: s'il y a du code que tu n'as pas rajouté volontairement, il y a un soucis ;-)
Bonne pratique: je me fais toujours une review moi même sur mes propres PR, pour éviter ce genre de choses. Et le fait de voir le code dans une autre interface permet aussi d'y apporter un regard neuf.

2022-10-05 12:30 UTC, cedricr approved these changes
:tada:

2022-10-06 09:55 UTC, merged