Feat/new search form
betagouv/dora-front pull request #132
Opened 2022-10-19 16:12 UTC by AlexandreCantin

2022-10-28 16:39 UTC, cedricr requested changes
Excellent!

Quelques remarques préliminaires:
- Le formulaire n'est pas censé être sur fond blanc?
- Les thématiques ne sont pas classées par ordre alpha
- La recherche de besoin ne matche que les débuts de ligne

2022-10-28 16:39 UTC, cedricr commented on src/lib/utils/choice.ts
> +export function getKeyFromChoice(choice: Choice): string {
Ce qui me dérange dans ce fichier, c'est qu'on a des méthodes avec des noms très génériques dont on s'attend qu'elles soient utilisables pour n'importe quel type de 'choices', alors qu'elles sont vraiment spécifiques de notre implémentation (discutable) des thématiques et besoins...
Par exemple, ici, est-ce que ça ne devrait pas être "getCategoryFromSubcategoryChoice" ou un truc dans le genre?

2022-10-28 16:39 UTC, cedricr commented on src/lib/utils/choice.ts
> +export function injectOptGroupAllOptionInSubCategories(
```suggestion
export function injectOptGroupAllOptionsInSubCategories(
```
?

2022-10-28 16:39 UTC, cedricr commented on src/lib/components/form/select/select-field.svelte
> +        c.label.toLowerCase().startsWith(filterText.toLocaleLowerCase())
a minima un contains plutot qu'un startsWith

2022-10-28 16:39 UTC, cedricr commented on src/lib/components/form/select/select-field.svelte
> +  let valuesSelectedInOptGroup: Record<string, number> = {};
```suggestion
  let numValuesSelectedInOptGroup: Record<string, number> = {};
```

Mais je pense que je laisserais tomber tout ce mecanisme de comptage de compliqué, qui au final sert juste à renseigner le  `@const hasSubValuesSelected` l. 340.
Tu pourrais le remplacer par un appel de fonction qui va compter à ce moment là les besoins selectionnés du groupe en cours.
De façon très approximative: 
```
{@const hasSubValuesSelected = optGroupHasSubValuesSelected(optGroup)}
```
avec
```
function countSubValuesSelected(optGroup) {
    return values.filter(v => v.split('--')[0] === optGroup.value).length > 0
}
```

2022-11-02 10:37 UTC, AlexandreCantin commented on src/lib/utils/choice.ts
> +export function getKeyFromChoice(choice: Choice): string {
J'ai opté pour `getCategoryKeyFromSubcategoryChoice` :)

2022-11-02 14:26 UTC, AlexandreCantin commented on src/lib/utils/city.ts
> +export function isInDeploymentDepartments(cityCode: string) {
J'ai modifié `services-options` pour renvoyer les départements en déploiement - avec la gestion côté front 🙂

2022-11-02 16:02 UTC, AlexandreCantin commented on src/lib/components/form/select/select-field.svelte
> +  let valuesSelectedInOptGroup: Record<string, number> = {};
En effet, c'est beaucoup plus simple 😅

2022-11-02 16:04 UTC, AlexandreCantin commented
- Le formulaire n'est pas censé être sur fond blanc ? Avec l'inversion entre le bloc de recherche et le bloc offreur, ce n'est plus le cas :)

- Les thématiques ne sont pas classées par ordre alpha => en effet, c'est corrigé :)

- La recherche de besoin ne matche que les débuts de ligne => modifié en passant le `includes` au lieu du `startsWith`

2022-11-03 12:57 UTC, AlexandreCantin commented on src/routes/recherche.svelte
> +    if (fee.length) {
Je vais créer un ticket sur Trello, on en discutera avec Aurélie lundi :)

2022-11-07 18:10 UTC, cedricr submitted a review, later dismissed

2022-11-09 16:58 UTC, cedricr approved these changes

2022-11-09 16:58 UTC, merged