Met à jour sveltekit
betagouv/dora-front pull request #14
Opened 2022-01-21 11:25 UTC by francoisromain

Corrige les breaking changes expliqués ici : https://github.com/sveltejs/kit/pull/3384

2022-01-21 11:28 UTC, francoisromain commented
De temps en temps, lorsque je lance `npm run dev`, j'ai une erreur 

```
[svelte-preprocess] PostCSS configuration was not passed or is invalid. If you expect to load it from a file make sure to install "postcss-load-config" and try again.
```

On dirait que svelte-preprocess ne trouve pas la config postcss.

2022-01-24 14:29 UTC, francoisromain commented
Corrige la gestion du SSR après la mise à jour de Sveltekit 1.0.0-next.222 https://github.com/sveltejs/kit/blob/master/packages/kit/CHANGELOG.md#100-next222

2022-01-24 14:39 UTC, cedricr requested changes

2022-01-24 14:39 UTC, cedricr commented on package.json
> +  "devDependencies": {
Attention, tout passer en devDependencies posait des problèmes au moment du deploiement sur scalingo.
Pour verifier si ça marche:
- fais un npm run build
- renomme ou supprime ton node_modules
- `node build`
Certains modules risquent de manquer

2022-01-24 14:39 UTC, cedricr commented on package.json
> -    "postcss": "^8.4.5",
plus nécessaire?

2022-01-24 14:39 UTC, cedricr commented on postcss.config.cjs
> -    // Some plugins, like postcss-nested, need to run before Tailwind,
ces commentaires me paraissaient potentiellement utiles non?

2022-01-24 14:39 UTC, cedricr commented on src/hooks.js
> +  "tableau-de-bord/structures",
/ initial ?

2022-01-24 14:39 UTC, cedricr commented on src/hooks.js
> +  "/sentry-debug-client",
il n'y a pas de sentry-debug-client, c'est sentry-debug non?

2022-01-24 14:39 UTC, cedricr commented on src/hooks.js
> +  "tableau-de-bord/structures",
et ce n'est pas exactement équivalent à ce qu'il y avait avant, mais pourquoi pas… Je pense qu'on pourrait meme mettre juste /tableau-de-bord

2022-01-24 15:58 UTC, francoisromain commented on src/hooks.js
> +const noSsrPaths = [
c'est la liste des routes qui n'ont pas de SSR.

2022-01-24 15:58 UTC, francoisromain commented on src/hooks.js
> +  "/sentry-debug-client",
je l'ai renommé pour pouvoir utiliser `pathname.startsWith` et le différencier de `sentry-debug-ssr`. ça te va ?

2022-01-24 15:58 UTC, francoisromain commented on src/hooks.js
> +  "tableau-de-bord/structures",
ok j'ai mis `/tablau-de-bord`

2022-01-24 15:59 UTC, francoisromain commented on package.json
> +  "devDependencies": {
corrigé. ça passe : `npm i && npm run build && rm -rf  node_modules/ && npm i --production && node build `

2022-01-24 16:00 UTC, francoisromain commented on postcss.config.cjs
> -    // Some plugins, like postcss-nested, need to run before Tailwind,
ok je les ai remis

2022-01-24 16:00 UTC, francoisromain commented on src/hooks.js
> +const noSsrPaths = [
on peut renommer cette variable si tu as une meilleure idée.

2022-01-24 16:04 UTC, francoisromain commented on package.json
> -    "postcss": "^8.4.5",
je l'ai remis

2022-01-25 09:53 UTC, cedricr commented on src/app.postcss
> +    avec cette erreur: https://github.com/sveltejs/svelte-preprocess/issues/298
L'issue 298 est fermée, et on ne comprend pas exactement le rapport avec ces classes là? Tu as compris pourquoi elles? Alors que c'est du CSS pur en plus?

2022-01-25 09:53 UTC, cedricr commented on package.json
>    "dependencies": {
On ne peut hélas pas mettre de commentaire dans les package.json, mais si tu as compris le pourquoi, j'aimerais bien au moins dans la description de la PR une explication de pourquoi certains packages doivent finir dans les dependencies et d'autre pas

2022-01-25 09:53 UTC, cedricr commented on src/lib/components/forms/field.svelte
> -      <div class="flex flex-col flex-1 grow min-h-[3rem]">
ça coinçait ça aussi???

2022-01-25 09:53 UTC, cedricr commented on src/lib/components/forms/input.svelte
> +  textarea {
ça repete la définition d'au-dessus

2022-01-25 09:53 UTC, cedricr commented on src/lib/components/forms/simple-autocomplete.svelte
> +    padding: 6px 12px;
De façon générale, je ne comprends pas trop pourquoi il y a des modifs de CSS dans cette PR

2022-01-25 09:53 UTC, cedricr commented on src/routes/_homepage/_search-form.svelte
> +      <div class="self-end mb-s16">
modif necessaire dans cette PR?

2022-01-25 09:53 UTC, cedricr commented on src/lib/components/forms/input.svelte
> +    @apply px-s12 py-s6 border border-gray-03 rounded outline-none placeholder-gray-text-alt focus:shadow-focus text-f14;
?

2022-01-25 09:53 UTC, cedricr commented on src/routes/auth/accepter-invitation.svelte
>    // We don't need ssr here, and don't want to api call done twice
Le commentaire était important dans ce cas, et on le perd en déplaçant le const ssr = false;
On risque de 
- corriger le pb global des fetch
- penser qu'on peut donc enlever cette histoire de SSR partout
- ce qui cassera toute la validation des emails
Je pense qu'il faut le remonter dans hooks.js, eventuellement en explicitant un peu mieux

2022-01-25 09:53 UTC, cedricr commented on src/routes/auth/reinitialiser-mdp.svelte
>  <script context="module">
même remarque

2022-01-25 09:53 UTC, cedricr commented on src/routes/auth/validation-email.svelte
> -  // We don't need ssr here, and don't want to api call done twice
même remarque

2022-01-25 10:10 UTC, francoisromain commented on package.json
>    "dependencies": {
ok. J'ai ajouté un bloc `"@comment dependencies":`

2022-01-25 10:10 UTC, francoisromain commented on src/app.postcss
> +    avec cette erreur: https://github.com/sveltejs/svelte-preprocess/issues/298
je me suis trompé de lien. J'ai changé.

2022-01-25 10:10 UTC, francoisromain commented on src/app.postcss
> +    avec cette erreur: https://github.com/sveltejs/svelte-preprocess/issues/298
Mais non, je ne comprend pas pourquoi ce bloc fait bugguer la compilation lorsqu'il est dans le composant `Button.svelte`

2022-01-25 10:10 UTC, francoisromain commented on src/lib/components/forms/input.svelte
> +  textarea {
ah oui bien vu.

2022-01-25 10:10 UTC, francoisromain commented on src/routes/_homepage/_search-form.svelte
> +      <div class="self-end mb-s16">
oui, ça permet de supprimer la porp `horizontalBottom` et le style associé `hz-bottom` qui fait parti du bloc de css qui fait tout bugguer dans `Button.svelte`. Aussi je trouve que c'est plus propre d'un point de vu css, car moins de styles spécifiques.

2022-01-25 10:10 UTC, francoisromain commented on src/routes/auth/accepter-invitation.svelte
>    // We don't need ssr here, and don't want to api call done twice
ok déplacé

2022-01-25 10:53 UTC, merged