Feat/result page new search form
betagouv/dora-front pull request #150
Opened 2022-11-08 10:36 UTC by AlexandreCantin

2022-11-08 16:23 UTC, cedricr requested changes

2022-11-08 16:23 UTC, cedricr commented on src/routes/_homepage/_search-result.svelte
> +  * Source: http://inclusive-components.design/cards/
ok, je vois l'interêt, même si le texte devien non selectionnable... mais dans ce cas pourquoi avoir le lien aussi sur la shortDesc?

2022-11-08 16:23 UTC, cedricr commented on src/routes/recherche.svelte
> +    return (
`services.every((s) => s.location === "a-distance")`, non?
Par contre est-ce que la definition d'un service national dans ce cas c'est un service à distance, ou c'est plutot un service dont la zone de diffusion est 'france entière' ?

2022-11-08 16:23 UTC, cedricr commented on src/routes/recherche.svelte
> +  const PAGE_LENGTH = 10;
constante en tête de fichier peut-être ?

2022-11-08 16:56 UTC, AlexandreCantin commented on src/routes/_homepage/_search-result.svelte
> +  const hasLocationBadged = result.distance || result.location === "a-distance";
Alors ça existe : https://www.wordreference.com/enfr/badged mais sûrement Tag serait plus logique :)

2022-11-08 17:20 UTC, cedricr commented on src/routes/_homepage/_search-result.svelte
> +  const hasLocationBadged = result.distance || result.location === "a-distance";
oui c'est juste que je vois pas ce qu'un participe passé vient faire dans ce contexte :rofl: 
Mais effectivement hasLocationTag ou mieux(?) hasLocationLabel me semble plus clair.

2022-11-09 14:46 UTC, AlexandreCantin commented on src/routes/_homepage/_search-result.svelte
> +  * Source: http://inclusive-components.design/cards/
J'ai mis un z-index à 2 pour que le texte reste sélectionnante malgré tout :)

2022-11-09 16:50 UTC, cedricr approved these changes

2022-11-09 16:52 UTC, merged