Fix unit tests
betagouv/dora-front pull request #172
Opened 2023-01-31 17:02 UTC by AlexandreCantin

Bon... 

Pour les tests e2e :
- certains sont obsolètes (éléments HTML et.ou textes modifiés depuis)
- on m'a imposé l'import avec les `.ts` sinon les modules ne sont pas trouvés...
-

2023-02-01 14:59 UTC, cedricr requested changes

2023-02-01 14:59 UTC, cedricr commented on package.json
> -    "preview": "vite preview --port 3000 --strictPort",
Une raison particulière d'enlever le port? Comme ça il va être dynamique, ça rend plus difficile d'avoir des bookmarks utiles

2023-02-01 14:59 UTC, cedricr commented on package.json
>      "build:test": "vite build --mode test",
le starterkit de sveltekit ne met plus ce --mode test (`npm create svelte@latest my-app`) 
Il est toujours nécessaire chez nous?

2023-02-01 14:59 UTC, cedricr commented on src/lib/utils/misc.ts
> +    /target="_blank"/g,
Comme ça c'est assez moche ;-) ta regexp n'est pas super spécifique, et il faudrait a minima que le replace soit fait **à l'interieur** du `insane()` sinon on risque assez facilement d'introduire des vulnérabilités.

Cela dit:
- en théorie, showdown le fait dejà tout seul (voir https://github.com/showdownjs/showdown/pull/670 ou https://github.com/showdownjs/showdown/issues/811), mais il est possible que ce soit insane qui l'enlève; voir ce qu'on a du faire dans `addlinkToUrls` dans le même fichier. En tout cas, regarde ce qui se passe si tu enlèves insane dans cet appel.
- n'oublie pas de tester `noopener`, c'est plus important que `nofollow`!

En tout cas, c'est la preuve que les tests unitaires sont utiles ;)

2023-02-02 09:15 UTC, AlexandreCantin commented on package.json
> -    "preview": "vite preview --port 3000 --strictPort",
Dans le fichier `playwright.config.ts`, on a :
```
 webServer: {
    command: "npm run build:test && npm run preview",
    port: 4173,
  },
```
Du coup, en fixant le port à `3000`, ça ne fonctionnait pas...

Bref, vu qu'on va retirer les tests e2e, on peut remettre le port :)

2023-02-02 09:25 UTC, AlexandreCantin commented on package.json
>      "build:test": "vite build --mode test",
Alors, ce `--mode test` permet l'utilisation du fichier `env.test` plutôt que `.env` => ce qui permet de placer `VITE_ENVIRONMENT=testing` et derrière ça de désactiver le ssr globalement avec  
`export const ssr = ENVIRONMENT === "testing" ? false : undefined;``

Encore une fois, si on supprime le e2e, toute cette mécanique devient inutile :)

2023-02-02 09:26 UTC, cedricr commented on package.json
>      "build:test": "vite build --mode test",
ok compris!

2023-02-02 09:27 UTC, cedricr commented on package.json
> -    "preview": "vite preview --port 3000 --strictPort",
ok, on aurait aussi pu changer le port à 4173, ou le mettre à 3000 dans la config PW, mais ok!

2023-02-02 09:54 UTC, AlexandreCantin commented on src/lib/utils/misc.ts
> +    /target="_blank"/g,
En effet, `showdown` le fait et `insane` l'enlève... Bien vu !
J'ai modifié les tests unitaires pour bien tester la présence de `noopener noreferrer`

2023-02-02 15:07 UTC, cedricr requested changes
Ça m'a l'air presque tout bon, je ne vois plus que le !.env.test dans le .gitignore

2023-02-02 17:14 UTC, cedricr approved these changes

2023-02-06 08:56 UTC, merged