Suppression du FieldWrapper obsolete
betagouv/dora-front pull request #175
Opened 2023-02-02 08:54 UTC by AlexandreCantin

Utilisation du FieldWrapper non obsolète

1er partie du ticket => https://trello.com/c/YTLDFfIM

2023-02-02 08:55 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Supprimer les inputs dupliqués => FieldWrapper](https://trello.com/c/YTLDFfIM/336-supprimer-les-inputs-dupliqu%C3%A9s-fieldwrapper)

2023-02-02 15:13 UTC, cedricr commented
Attention, ça casse l'alignement 
![image](https://user-images.githubusercontent.com/7826756/216363347-99a4a547-8216-436c-8063-2e5302e1492e.png)

2023-02-09 15:45 UTC, cedricr commented
Le focus est pas joli joli… 
![image](https://user-images.githubusercontent.com/7826756/217862928-0a940c95-3dee-46ea-aac6-f324b0f66b24.png)

2023-02-09 16:28 UTC, cedricr requested changes
Voir commentaire

2023-02-15 17:37 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +  .subcategories-search :global(.field-wrapper) {
je suis pas super fan de tout ces :global... ça rend le CSS vraiment super difficile à comprendre. 
Si tu me dis que c'est juste temporaire en attendant qu'on unifie aussi le reste (et j'ai l'impression que c'est le cas...), ça me va.

2023-02-16 10:16 UTC, AlexandreCantin commented on src/lib/components/specialized/service-search.svelte
> +  .subcategories-search :global(.field-wrapper) {
Le problème majeur, qu'on a aussi avec les <SelectField />, c'est qu'on utilise des composants communs contenant des options de présentation qui ne sont pas forcément adapter à tous les cas figures 😰
Par exemple, le FieldWrapper définit un design `1/3` - `2/3` de base - qui n'est pas compatible avec le besoin dans la recherche de besoins de la HP...

Peut-être qu'une autre voie serait à creuser !

2023-02-16 11:13 UTC, cedricr commented on src/lib/components/specialized/service-search.svelte
> +  .subcategories-search :global(.field-wrapper) {
PS: ça peut faire un bon sujet pour notre prochaine séance de pair-prog

2023-02-27 12:59 UTC, cedricr approved these changes

2023-02-28 08:47 UTC, merged