Pas d'auto-scroll sur les onglets des structures
betagouv/dora-front pull request #178
Opened 2023-02-06 14:08 UTC by AlexandreCantin

https://trello.com/c/cgPxD6gJ/265-pr%C3%A9server-le-scroll-au-changement-donglets-sur-la-page-structures

2023-02-06 14:08 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Préserver le scroll au changement d'onglets sur la page structures](https://trello.com/c/cgPxD6gJ/265-pr%C3%A9server-le-scroll-au-changement-donglets-sur-la-page-structures)

2023-02-09 16:10 UTC, cedricr requested changes

2023-02-09 16:10 UTC, cedricr commented on src/lib/components/display/tabs-links.svelte
> +  import type { TabItem } from "$lib/types";
Remarque générale: tabs-link.svelte est utilisé uniquement dans les structures, donc je le descendrais dans routes/structure. Ce qui diminuerait un peu la confusion entre tabs-link.svelte et tabs.svelte, qui sont cote à cote dans components/display, et qui font presque la même chose.

Et de la même façon, je définirais le type TabItem ici, là encore pour éviter la confusion.

2023-02-09 16:10 UTC, cedricr commented on src/lib/components/display/tabs-links.svelte
> +  export let noScrollOnChange = false;
On a un seul usage de ce composant, et on change son fonctionnement: pas besoin d'introduire une option qui n'est pas nécessaire pour l'instant

2023-02-09 16:10 UTC, cedricr commented on src/routes/structures/[slug]/header.svelte
> +    <Tabs items={tabs} itemId={tabId} noScrollOnChange />
Appelons le TabsLink plutot que Tabs, puisque c'est le nom du composant. La encore, on diminue la confusion.

2023-02-09 16:10 UTC, cedricr commented on src/lib/components/display/tabs-links.svelte
> +  export let itemId: string | undefined = undefined;
Il n'y a pas de raison de le rendre optionnel à mon avis.
```suggestion
  export let itemId: string;
```

2023-02-09 16:10 UTC, cedricr commented on src/lib/components/display/tabs-links.svelte
> +  export let items: TabItem[] = [];
je ne suis pas fan du tableau vide ici, mais le parent a été écrit avec un tableau qui se rempli dynamiquement… donc ok.

2023-02-13 11:14 UTC, AlexandreCantin commented on src/routes/structures/[slug]/header.svelte
> +    <Tabs items={tabs} itemId={tabId} noScrollOnChange />
Confusion que j'ai faite !

2023-02-13 11:17 UTC, cedricr commented on src/routes/structures/[slug]/header.svelte
> +    <Tabs items={tabs} itemId={tabId} noScrollOnChange />
Hum je sais pas ça traine depuis un moment ces 2 tabs! Et si c'est vraiment toi dans ce cas, on a tous été coupables ailleurs à un moment ou un autre :rofl:

2023-02-13 11:41 UTC, AlexandreCantin commented on src/routes/structures/[slug]/header.svelte
> +    <Tabs items={tabs} itemId={tabId} noScrollOnChange />
Alors je l'ai faite en regardant si on avait plusieurs instances de `<Tabs />` =)

2023-02-13 12:17 UTC, cedricr approved these changes

2023-02-13 14:48 UTC, merged