NPS offreur-chercheur en commun
betagouv/dora-front pull request #179
Opened 2023-02-06 17:49 UTC by AlexandreCantin

https://trello.com/c/EgvZNnPk/350-ajustement-des-nps-pour-le-gip

2023-02-06 17:50 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Ajustement des NPS pour le GIP](https://trello.com/c/EgvZNnPk/350-ajustement-des-nps-pour-le-gip)

2023-02-09 16:24 UTC, cedricr requested changes

2023-02-09 16:24 UTC, cedricr commented on src/lib/components/specialized/tally-nps-popup.svelte
> +              saveNpsCloseDate(formId);
saveNpsFormDateClosed

2023-02-09 16:24 UTC, cedricr commented on src/lib/utils/nps.ts
> +  NPS_RECOMMANDATION_FORM_ID = "nrDeXN",
`Recommandation` n'est pas anglais, mais je ne vois pas ce que tu veux dire là. Est-ce qu'on ne veut pas juste NPS_FORM_ID ?

2023-02-09 16:24 UTC, cedricr commented on src/routes/services/[slug]/+page.svelte
> +          hiddenFields={{ user: "offreur" }}
est-ce que ça vaut pas le coup de les typer?

2023-02-13 10:03 UTC, AlexandreCantin commented on src/routes/services/[slug]/+page.svelte
> +          hiddenFields={{ user: "offreur" }}
D'un formulaire Tally a un autre, les `hiddenFields` vont être différents...

Par conséquent, je pense qu'un typage avec des clés trop précises, on va finir avec une fusion de tous les `hiddenFields` de Dora et je suis pas forcément en faveur de cela... 🫤
Par contre, je suis pas contre un formatage plus générique du type `Record<string,string>` (même si moins pertinent)

2023-02-13 10:04 UTC, AlexandreCantin commented on src/lib/utils/nps.ts
> +  NPS_RECOMMANDATION_FORM_ID = "nrDeXN",
Mais en effet, sur Tally, le NPS porte le nom de `NPS_DORA_ALL` donc `NPS_FORM_ID ` ne me paraît pas déconnant..

2023-02-13 10:20 UTC, AlexandreCantin commented on src/routes/services/[slug]/+page.svelte
> +          hiddenFields={{ user: "offreur" }}
Bon au final, j'ai fait le typage avec 
```
export type HiddenFields = {
  user: "offreur" | "chercheur";
};
```

On verra si cela devient problématique si `HiddenFields` prend trop d'ampleur :)

2023-02-13 10:57 UTC, cedricr commented on src/routes/services/[slug]/+page.svelte
> +          hiddenFields={{ user: "offreur" }}
Yes d'accord avec tout ce que tu as dit, et effectivement, ajoutons la compléxité quand elle devient nécessaire ;-)

2023-02-13 10:59 UTC, cedricr approved these changes

2023-02-13 12:06 UTC, merged