Longueur de 0 en l'absence de valeur
betagouv/dora-front pull request #180
Opened 2023-02-09 10:18 UTC by AlexandreCantin

https://trello.com/c/jakkZy4D/357-undefined-140-caract%C3%A8res-%C3%A0-louverture

2023-02-09 10:19 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [undefined/140 caractères à l'ouverture](https://trello.com/c/jakkZy4D/357-undefined-140-caract%C3%A8res-%C3%A0-louverture)

2023-02-09 15:54 UTC, cedricr requested changes

2023-02-09 15:54 UTC, cedricr commented on src/lib/components/forms/fields/basic-input-field.svelte
> +          {value?.length ?? 0}/{maxLength} caractères
pas nécessaire, on est dans un {#if value}. Le point d'interrogation initial n'était pas nécessaire non plus.
```suggestion
          {value.length}/{maxLength} caractères
```

2023-02-09 15:54 UTC, cedricr commented on src/lib/components/forms/fields/textarea-field.svelte
> +          {value?.length ?? 0}/{maxLength} caractères
même remarque

2023-02-09 15:54 UTC, cedricr commented on src/lib/components/forms/fields/addable-multiselect-field.svelte
> +                {newValue?.length ?? 0}/{maxLength} caractères
ce n'est pas géré comme ça dans les deux autres composants: on n'affiche pas le texte si la chaine est falsy.
Donc plutot entourer avec un 
`{#if value && maxLength != null}`

2023-02-09 16:55 UTC, AlexandreCantin commented on src/lib/components/forms/fields/addable-multiselect-field.svelte
> +                {newValue?.length ?? 0}/{maxLength} caractères
En effet, je n'avais pas remarqué que ça fonctionnait ainsi 

Par contre, en terme d'accessibilité, cela risque de poser un problème car on découvre la limitation lors de la saisie alors qu'elle devrait être visible dès l'apparition dès le début...

2023-02-09 17:06 UTC, cedricr commented on src/lib/components/forms/fields/addable-multiselect-field.svelte
> +                {newValue?.length ?? 0}/{maxLength} caractères
Ça ne me dérange pas qu'on l'affiche dès le début, pourvu que ce soit le cas partout -- verifie peut-etre ce qu'en pense Andrei avant. Eventuellement en sr-only? Mais ça complexifierait pas mal le code pour rien je pense.

2023-02-13 10:27 UTC, AlexandreCantin commented on src/lib/components/forms/fields/addable-multiselect-field.svelte
> +                {newValue?.length ?? 0}/{maxLength} caractères
On va laisser comme ça pour le moment.
Je ne suis même pas sûr que cela posera un problème niveau accessibilité... mais je vais poser la question :)

2023-02-13 10:53 UTC, cedricr approved these changes

2023-02-13 12:06 UTC, merged