A11y/global corrections
betagouv/dora-front pull request #187
Opened 2023-02-14 10:53 UTC by AlexandreCantin

https://trello.com/b/Ee4NdPU9/dora-backlog-tech

2023-02-15 17:23 UTC, cedricr requested changes

2023-02-15 17:23 UTC, cedricr commented on src/lib/components/display/button-menu.svelte
> +  const id = crypto.randomUUID();
Je me demande si dans ces cas là, ça ne serait pas mieux de mettre un truc du genre `button-label-${crypto.randomUUID()}`, principalement pour aider le debugging... :thinking:

2023-02-15 17:23 UTC, cedricr commented on src/lib/components/display/button-menu.svelte
> +      extraAttributes={{
on perd le typage, etc. Pourquoi ne pas les rajouter directement comme attributs?

2023-02-15 17:23 UTC, cedricr commented on src/lib/components/display/button.svelte
> +  <span class:sr-only={hideLabel}>{label}</span>
bien pour l'instant, mais il me semble que les boutons avec seulement une icone, c'est déconseillé de toute façon non?

2023-02-15 17:23 UTC, cedricr commented on src/routes/_index/menu.svelte
> +    <ButtonMenu label="Menu d'aide" hideLabel icon={questionFillIcon}>
```suggestion
    <ButtonMenu label="Menu d’aide" hideLabel icon={questionFillIcon}>
```

2023-02-15 17:23 UTC, cedricr commented on src/routes/_index/skip-link.svelte
> +  class="sr-only top-s32 left-s32 z-20 rounded bg-white text-f16 font-bold text-magenta-cta outline-none hover:text-magenta-hover  focus:not-sr-only focus:absolute focus:p-s8 focus:shadow-focus"
c'était quoi le pb de la transparence?

2023-02-15 23:18 UTC, AlexandreCantin commented on src/lib/components/display/button.svelte
> +  <span class:sr-only={hideLabel}>{label}</span>
C'est pas déconseillé - mais il faut à minima un label pour les lecteurs d'écran

2023-02-15 23:19 UTC, AlexandreCantin commented on src/routes/_index/skip-link.svelte
> +  class="sr-only top-s32 left-s32 z-20 rounded bg-white text-f16 font-bold text-magenta-cta outline-none hover:text-magenta-hover  focus:not-sr-only focus:absolute focus:p-s8 focus:shadow-focus"
Le lien se chevauchait avec le header (et surtout le logo du ministère)
En fait, je ne comprends pas pourquoi j'avais ce lien avec un fond transparent... 🙃

2023-02-15 23:20 UTC, AlexandreCantin commented on src/routes/_index/menu.svelte
> +    <ButtonMenu label="Menu d'aide" hideLabel icon={questionFillIcon}>
Il faudra que tu me dises les touches au clavier pour récupérer cet apostrophe... 😅

2023-02-15 23:28 UTC, AlexandreCantin commented on src/lib/components/display/button-menu.svelte
> +  const id = crypto.randomUUID();
En effet, ça serait intéressant pour le debugging si besoin
Par contre, je vais opter pour `button-menu-${crypto.randomUUID()`, ça aidera encore mieux 😃

2023-02-16 09:25 UTC, cedricr commented on src/routes/_index/skip-link.svelte
> +  class="sr-only top-s32 left-s32 z-20 rounded bg-white text-f16 font-bold text-magenta-cta outline-none hover:text-magenta-hover  focus:not-sr-only focus:absolute focus:p-s8 focus:shadow-focus"
hum, si tu regardes l'historique, j'avais modifié ce skip-link pour passer par un sr-only, au lieu des trucs qui étaient fait à la main avant, mais j'ai du me planter dans le style focusé!

2023-02-16 09:26 UTC, cedricr commented on src/routes/_index/menu.svelte
> +    <ButtonMenu label="Menu d'aide" hideLabel icon={questionFillIcon}>
tu es sur quel OS? Et quel type de clavier?

2023-02-16 15:58 UTC, AlexandreCantin commented on src/lib/components/display/button-menu.svelte
> +      extraAttributes={{
du coup, on est bon @cedricr ? 😅

2023-02-16 16:32 UTC, cedricr approved these changes

2023-02-16 16:33 UTC, cedricr commented on src/lib/components/display/button-menu.svelte
> +      extraAttributes={{
:+1: :+1: :+1:

2023-02-16 16:33 UTC, merged