Fix UI cards
betagouv/dora-front pull request #216
Opened 2023-03-15 15:36 UTC by AlexandreCantin

2023-03-16 13:27 UTC, cedricr requested changes

2023-03-16 13:27 UTC, cedricr commented on src/lib/utils/date.ts
> +  prefix = "Actualisé"
Je ne suis pas convaincu par
- le fait de passer un prefixe ici, dans une méthode qui se veut géneraliste; sans certains cas on va préférer un suffixe, dans d'autres rien. Je pense que c'est mieux de laisser l'appelant ajouter ce qu'il veut
- le fait de mettre une valeur par défaut qui est hyper spécifique à un appel donné.

Note que je n'aurais pas de pb avec ces deux points si c'était une methode locale à une route, ou à un fichier svelte.

2023-03-16 16:50 UTC, AlexandreCantin commented on src/routes/structures/[slug]/services/service-card.svelte
> +  $: updateStatusData = computeUpdateStatus(service);
Oui j'ai loupé celui-là :)

2023-03-16 17:12 UTC, AlexandreCantin commented on src/lib/utils/date.ts
> +  prefix = "Actualisé"
Du coup, j'ai retiré le `prefix` de cette fonction :)
Et je l'ai spécifié au niveau du composant `<RelativeDateLabel />`

2023-03-16 17:28 UTC, AlexandreCantin commented on src/routes/services/[slug]/service-update-status-as-contributor.svelte
> +            <RelativeDateLabel date={service.modificationDate} />
J'aime bien l'idée et j'ai modifié en ce sens !
En fait, je ne vois pas de scénario où il est pertinent de garder la date relative en cas d'impression 🙂

2023-03-16 17:30 UTC, AlexandreCantin commented on src/lib/components/display/relative-date-label.svelte
> +  import { computeRelativeDateLabel } from "$lib/utils/date";
Alors du coup, en déplaçant la logique d'impression dans `<RelativeDateLabel />`, il prend davantage son sens.
J'ai aussi déplacé la fonction `computeRelativeDateLabel` dans `<script lang="ts" context="module">`

2023-03-16 17:33 UTC, cedricr commented on src/routes/services/[slug]/service-update-status-as-reader.svelte
> +                <RelativeDateLabel date={service.modificationDate} />
ah oui pardon, mais dans ma tête il n'y étais déjà plus :rofl:

2023-03-16 17:34 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +  import { computeRelativeDateLabel } from "$lib/utils/date";
effectivement!

2023-03-16 18:06 UTC, cedricr requested changes

2023-03-16 18:06 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +<svelte:element this={htmlTag} class="hidden print:inline">
ok, ça marche comme ça, mais je trouve ça un peu trop 'malin' comme code ;-)
Etant donné que la sémantique du \<strong\> ne me parait pas super importante ici, est qu'un truc comme ça ne serait pas aussi bien, et plus facile à lire?

```
<span class="hidden print:inline" class:font-bold={bold}>
  {prefix}&nbsp;<DateLabel {date} />
</span>
<span class="print:hidden" class:font-bold={bold}>
  {prefix}&nbsp;{computeRelativeDateLabel(date)}
</span>
```

2023-03-20 10:16 UTC, AlexandreCantin commented on src/lib/components/display/relative-date-label.svelte
> +<svelte:element this={htmlTag} class="hidden print:inline">
J'ai eu des doutes sur l'aspect sémantique - on verra si ça pose un souci un jour ou non 😅

2023-03-20 10:27 UTC, AlexandreCantin commented on src/lib/components/display/relative-date-label.svelte
> +  export let prefix = "Actualisé le";
Je suis d'accord sur le fait que le `"Actualisé le"` est trop spécifique pour être par défaut...
Je vais faire un entre-deux et imposé le préfix comme paramètre :)

2023-03-20 10:36 UTC, AlexandreCantin commented on src/lib/components/display/relative-date-label.svelte
> +  export let prefix = "Actualisé le";
D'ailleurs je me rends compte que cela donnait "Actualisé le il y a 3 jours"...

2023-03-24 10:09 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +  export let prefix = "Actualisé le";
Mieux, mais c'est dommage de ne pas autoriser un préfixe vide. Sur une date de modification par exemple, ça ferait complètement sens de seulement afficher "il y a trois jours"

2023-03-24 10:13 UTC, cedricr requested changes

2023-03-24 10:13 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +  export let prefix: string;
voir commentaire
```suggestion
  export let prefix = "";
```

2023-03-24 10:13 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +  {prefix}&nbsp;<DateLabel {date} />
pas convaincu par la nécessité d'un `&nbsp;` ici; et si le prefixe est vide, il faut faire sauter l'espace. 
Du coup, qqchose du genre
```suggestion
  {prefix ? `${prefix} ` : ``}<DateLabel {date} />
```

2023-03-24 10:13 UTC, cedricr commented on src/lib/components/display/relative-date-label.svelte
> +  {prefix}&nbsp;{computeRelativeDateLabel(date)}
idem

2023-03-28 10:00 UTC, AlexandreCantin commented on src/lib/components/display/relative-date-label.svelte
> +  {prefix}&nbsp;<DateLabel {date} />
Du coup, je suis parti sur cette solution 👍

2023-03-29 09:16 UTC, cedricr approved these changes

2023-04-03 07:06 UTC, merged