Onboarding design fixes
betagouv/dora-front pull request #218
Opened 2023-03-16 09:00 UTC by AlexandreCantin

https://trello.com/c/pMswYazN/234-fiche-structure-onboarding-empty-spaces

2023-03-16 09:45 UTC, AlexandreCantin commented
Retour en _draft_ car le périmètre a été modifié !

2023-03-16 17:12 UTC, cedricr requested changes
Sous reserve de la réponse à ma question sur mattermost !
https://mattermost.incubateur.net/betagouv/pl/9ynqm1wy4jr6dya6anw8oc9zqo

2023-03-16 17:12 UTC, cedricr commented on src/routes/structures/[slug]/+page.svelte
> +{#if !!$structure.models?.length && $structure.canEditServices}
Pas d'objection sur l'usage du !!, mais il est vraiment inutile dans ce genre de contexte

2023-03-16 17:12 UTC, cedricr commented on src/routes/structures/[slug]/quick-start.svelte
> +    await modifyStructure({ ...structure, quickStartDone: true });
modifyStructure fait un PATCH, donc tu n'as pas besoin en théorie de renvoyer toutes ses données
```suggestion
    await modifyStructure({ quickStartDone: true });
```

2023-03-16 17:12 UTC, cedricr commented on src/routes/structures/[slug]/quick-start.svelte
> +    showQuickStart = canShowQuickStart(structure);
inutilement compliqué maintenant que la condition est plus simple;
la fonction canShowQuickStart peut disparaitre et tu utilises !structure.quickStartDone à la place

2023-03-16 17:12 UTC, cedricr commented on src/routes/structures/[slug]/quick-start.svelte
> +  ) {
on n'était pas obligés de mettre le boolean à jour quand les conditions sont remplies, et ne le garder que pour dénoter l'action 'je ne veux plus voir ce truc', mais ok

2023-03-16 17:12 UTC, cedricr commented on src/routes/structures/[slug]/quick-start.ts
>  export function hasOneService(structure: Structure): boolean {
Mal nommé: hasAtLeastOneService, or hasServices. On ne veut pas savoir s'ils sont publiés? Sinon ça serait une étape interessante à rajouter.

2023-03-27 14:01 UTC, cedricr approved these changes

2023-03-27 14:04 UTC, merged