Confirm modal when leaving ongoing form
betagouv/dora-front pull request #222
Opened 2023-03-21 10:28 UTC by AlexandreCantin

https://trello.com/c/wQ6QFUoV/626-alerte-enregistrement-%C3%A0-la-saisie-sortie-du-formulaire

Attention : `svelteKit` a un fonctionnement différent en fonction du type d'action (refresh, navigation interne...) et ce n'est pas la même alerte (native du navigateur ou `window.confirm`) qui se déclenche  => https://kit.svelte.dev/docs/modules#$app-navigation-beforenavigate

2023-03-24 11:23 UTC, cedricr requested changes

2023-03-24 11:23 UTC, cedricr commented on src/lib/components/forms/form.svelte
> +        "Êtes-vous sûr·e de vouloir quitter cette page ? Les modifications que vous avez effectuées ne seront pas sauvegardées."
le · n'est pas accessible, j'ai lancé une discussion sur Trello.

2023-03-24 11:23 UTC, cedricr commented on src/lib/components/forms/form.svelte
> +  export let hasUnsavedChange = false;
pourquoi le export?

2023-03-24 11:23 UTC, cedricr commented on src/lib/components/forms/form.svelte
> +        hasUnsavedChange = false;
C'est pas idéal parce que si on modifie un champ et qu'on efface la modification, ça ne devrait pas bloquer la navigation, mais ça me parait pas trop grave pour l'instant

2023-03-24 11:23 UTC, cedricr commented on src/lib/components/forms/form.svelte
> +    const oldHasUnsavedChange = hasUnsavedChange;
ça me parait plus simple de mettre le hasUnsavedChange à true juste après l'appel à onSuccess, ce qui rend la sauvegarde de l'état initial inutile.

2023-03-24 14:09 UTC, cedricr commented on src/lib/components/forms/form.svelte
> +        "Êtes-vous sûr·e de vouloir quitter cette page ? Les modifications que vous avez effectuées ne seront pas sauvegardées."
on part sur le message par défaut de firefox

2023-03-28 15:00 UTC, AlexandreCantin commented on src/lib/components/forms/form.svelte
> +        hasUnsavedChange = false;
Oui, pour le moment, je ne souhaite pas partir sur un diff mais se fier uniquement à des `onChange`
Peut-être que cela évoluera avec le temps...

2023-03-28 15:03 UTC, AlexandreCantin commented on src/lib/components/forms/form.svelte
> +  export let hasUnsavedChange = false;
Un relicat... 🫤

2023-03-30 16:08 UTC, merged