Ajoute storybook
betagouv/dora-front pull request #23
Opened 2022-02-10 18:18 UTC by francoisromain

2022-02-10 18:21 UTC, francoisromain commented
J'ai utilisé la version `vite` de storybook. https://github.com/eirslett/storybook-builder-vite
Il y a des problèmes de dépendances et `npm i` est interrompu par une erreur. Il faut faire `npm i -f`. 
Il y a aussi quelques tweaks que j'ai pris ici: https://codingcat.dev/tutorial/integrating-storybook-with-sveltekit

2022-02-15 18:49 UTC, francoisromain commented
@cedricr 

- sur les vulnérabilité, je n'ai pas vraiment de solution. J'ai utilisé une version alpha de storybook 6.5 qui est activement développé. On peut croiser les doigts pour que ça soit absorbé rapidement. 
- le `npm i -f` n'est utilie que lors de la première instal. Cela vient de `@storybook/addon-svelte-csf` qui n'est pas officiellement compatible avec la version alpha.
- `@storybook/addon-docs` est maintenant dans les dépendances. cette erreur est résolue.

2022-02-16 09:57 UTC, cedricr requested changes

2022-02-16 09:57 UTC, cedricr commented on src/app.postcss
> +    font-family: swap, sans-serif;
hum le "font-sans" qui était dans le tag body de app.html se referait à ça dans le config tailwind:
    fontFamily: {
      sans: ["Marianne"],
    },
donc Marianne… alors que là tu vas utiliser un sans-serif générique, non?

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/button.svelte
> +  export let secondary = false;
et le tertiary

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/button.svelte
> -  export let nogrow = false;
tu l'as géré autrement?

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/forms/alert.svelte
> -  {#if iconOnRight}
c'était jamais utilisé? Et pas dans le design system?

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/label.svelte
> -  {#if iconOnRight}
même remarque

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/link-button.svelte
> +
Je comprends pas, tu as redupliqué le Button au lieu d'utiliser la composition?

2022-02-16 09:57 UTC, cedricr commented on src/routes/services/form/_nav-buttons.svelte
> -        tertiary
c'est pas les mêmes!

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/button-menu.svelte
> -  export let iconOnLeft = undefined,
Sûr que le DS ne propose pas les deux options?

2022-02-16 09:57 UTC, cedricr commented on src/lib/components/button.svelte
> +  export let iconOnRight = false;
oui!

2022-02-16 10:21 UTC, francoisromain commented on src/lib/components/button.svelte
> +  export let small = false;
oui. validé par Andrei.

2022-02-16 10:21 UTC, francoisromain commented on src/lib/components/button.svelte
> +  export let secondary = false;
oui. validé par Andrei.

2022-02-16 10:21 UTC, francoisromain commented on src/lib/components/button.svelte
> -  export let nogrow = false;
il ne sert plus

2022-02-16 10:22 UTC, francoisromain commented on src/lib/components/forms/alert.svelte
> -  {#if iconOnRight}
non pas utilisé. Suppression validé par Andrei

2022-02-16 10:22 UTC, francoisromain commented on src/lib/components/label.svelte
> -  {#if iconOnRight}
même réponse

2022-02-16 10:22 UTC, francoisromain commented on src/app.postcss
> +    font-family: swap, sans-serif;
je corrige

2022-02-16 10:23 UTC, francoisromain commented on src/lib/components/link-button.svelte
> +
oui le bouton dans un lien, c'est pas très propre du point de vue sémantique. Et les deux composants n'ont pas exactement les mêmes props.

2022-02-16 10:23 UTC, francoisromain commented on src/routes/services/form/_nav-buttons.svelte
> -        tertiary
inutilisé

2022-02-16 10:24 UTC, francoisromain commented on src/lib/components/button-menu.svelte
> -  export let iconOnLeft = undefined,
par défault, l'icone est à gauche. Si on veut la placer à droite on utilise `iconOnRight`

2022-02-16 10:24 UTC, francoisromain commented on src/lib/components/button.svelte
> +  export let iconOnRight = false;
ok :D

2022-02-16 11:48 UTC, cedricr commented on src/lib/components/button-menu.svelte
> -  export let iconOnLeft = undefined,
oui mais iconOnRight n'est pas exposé non plus dans ButtonMenu (mais encore une fois, ce n'est peut-etre plus nécessaire?)

2022-02-16 11:56 UTC, cedricr commented on src/lib/components/link-button.svelte
> +
La duplication me parait quand même génante, surtout sur un composant qui est assez complexe. Ok pour l'instant, mais à terme on pourrait peut-être surveiller https://github.com/sveltejs/svelte/pull/6898, et créer dynamiquement un <a> ou un <button> quand ce sera possible.

2022-02-16 11:56 UTC, cedricr approved these changes

2022-02-16 12:19 UTC, francoisromain commented on src/lib/components/button-menu.svelte
> -  export let iconOnLeft = undefined,
non il n'est pas utilisé dans celui la

2022-02-16 12:19 UTC, merged