Unifier le code front et l'UI des fiches services et des modèles
betagouv/dora-front pull request #239
Opened 2023-04-12 12:46 UTC by AlexandreCantin

https://trello.com/c/xjmGD56U/7-unifier-le-code-front-et-lui-des-fiches-services-et-des-mod%C3%A8les

Note : il manque la transparence pour les images

2023-04-12 14:01 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Unifier le code front et l'UI des fiches services et des modèles](https://trello.com/c/xjmGD56U/7-unifier-le-code-front-et-lui-des-fiches-services-et-des-mod%C3%A8les)

2023-04-13 15:26 UTC, cedricr requested changes

2023-04-13 15:26 UTC, cedricr commented on src/routes/services/[slug]/+page.svelte
> -      <div class="presentation">
il reste du nettoyage à faire dans le CSS non?

2023-04-13 15:26 UTC, cedricr commented on src/routes/modeles/[slug]/+page.svelte
> +          <UpdateStatusIcon updateStatus="NOT_NEEDED" />
ça me parait bizarre d'avoir ça dans les modèles???

2023-04-13 15:26 UTC, cedricr commented on src/routes/modeles/[slug]/+page.svelte
> +            label="Créer un service"
service???

2023-04-13 15:26 UTC, cedricr commented on src/routes/modeles/[slug]/model-header.svelte
c'est un peu dommage que ça reste different des services

2023-04-13 16:00 UTC, AlexandreCantin commented on src/routes/services/[slug]/+page.svelte
> -      <div class="presentation">
Arf, je pensais avoir fait un couper-coller 😅

2023-04-13 16:03 UTC, AlexandreCantin commented on src/routes/modeles/[slug]/+page.svelte
> +            label="Créer un service"
Oui, "Créer un service" depuis le modèle :)

2023-04-13 16:12 UTC, AlexandreCantin commented on src/lib/assets/style/corner-left-lightblue.png
Je me suis cassé les dents dessus…  mais j'ai eu une idée pour tenter autre chose :}

2023-04-13 18:31 UTC, cedricr commented on src/lib/assets/style/corner-left-lightblue.png
au cas où, je peux essayer de chercher dans l'historique, c'était fait en CSS dans le temps.

2023-04-14 08:57 UTC, AlexandreCantin commented on src/routes/modeles/[slug]/model-header.svelte
Entre le `<Bookmarkable>` et les informations différentes… J'ai préféré ne pas fusionner les deux.

2023-04-14 09:13 UTC, AlexandreCantin commented on src/lib/components/specialized/services/display/service-beneficiaries.svelte
Alors oui, ça ne me gêne pas de le faire mais dans un second temps…

En fait, cela posait deux problèmes majeurs :
- le nom à donner à ce dossier… `(modele-service)` ?
- et surtout, la PR devenait impossible à reviewer… avec 169 fichiers modifiés => du coup, je compte enchaîner sur cette modification 

==> j'ai créé un second ticket pour cela : https://trello.com/c/Dm4Ckx3c/706-part-2-unifier-le-code-services-et-des-mod%C3%A8les-dans-un-m%C3%AAme-dossier

2023-04-17 13:51 UTC, cedricr commented on src/routes/modeles/[slug]/+page.svelte
> +          <UpdateStatusIcon updateStatus="NOT_NEEDED" />
ok bof, mais ça me parait un compromis acceptable pour l'instant

2023-04-17 13:51 UTC, cedricr commented on src/routes/modeles/[slug]/model-header.svelte
ok, on verra dans le futur si ça devient génant

2023-04-19 09:12 UTC, AlexandreCantin commented on src/lib/components/display/centered-grid.svelte
> +      ? 'md:rounded-tl-[30px] md:rounded-tr-[30px] lg:rounded-tl-[45px] lg:rounded-tr-[45px] xl:rounded-tl-[60px] xl:rounded-tr-[60px]'
Je n'y ai pas pensé… 😅

2023-04-25 13:07 UTC, cedricr approved these changes

2023-04-25 18:15 UTC, merged