New header design
betagouv/dora-front pull request #250
Opened 2023-05-02 11:54 UTC by AlexandreCantin

2023-05-03 14:27 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mettre en place le nouveau header](https://trello.com/c/P9R2nd8P/228-mettre-en-place-le-nouveau-header)

2023-05-04 09:21 UTC, cedricr requested changes
Première passe de review, c'est top!

2023-05-04 09:21 UTC, cedricr commented on src/lib/components/display/dropdown-menu.svelte
> +    background-color: var(--col-white);
Pourquoi t'es pas passé par du tailwind ici? J'aimerais bien qu'on se débarasse de ces variables à terme, c'est plus une survivance qu'autre chose

2023-05-04 09:21 UTC, cedricr commented on src/lib/components/display/dropdown-menu.svelte
Ok je vois ce que tu voulais dire avec ton commentaire sur les dropdown differents.
En attendant que ça se resolve coté design, je pense qu'il faut a minima rajouter un commentaire en début de fichier, pour expliquer pourquoi il y a deux types de dropdown different, et lequel utiliser dans quelle circonstance.

2023-05-04 09:21 UTC, cedricr commented on src/routes/_index/menu-mon-compte.svelte
> +  {#if structures.length !== 0}
qu'est-ce que ça fait dans 'Mon compte' ça? Il faut pas renommer le fichier a minima, ou plutot faire un composant par menu?

2023-05-04 09:21 UTC, cedricr commented on src/routes/_index/sub-menu.svelte
> +  export let mobileDesign = false;
Je te laisse juge de ça, mais j'ai l'impression qu'il y a deux composants assez differents en un ici; est-ce que ça n'aurait pas été plus clair d'avoir un composant desktop et un mobile, plutot que d'avoir des 'mobileDesign' imbriqués partout?

2023-05-04 10:31 UTC, AlexandreCantin commented on src/routes/_index/menu-mon-compte.svelte
> +  {#if structures.length !== 0}
En effet, je vais séparer les deux :)

2023-05-04 12:50 UTC, AlexandreCantin commented on src/routes/_index/sub-menu.svelte
> +  export let mobileDesign = false;
Pour le coup, je préfère en garder un seul :)
En fait, je n'ai pas vraiment envie de rajouter encore plus de duplication (car je trouve qu'il y en a déjà assez avec les `dropdown`)

2023-05-15 08:27 UTC, cedricr approved these changes

2023-05-17 08:13 UTC, merged