Mise à jour des servies en masse depuis les modèles
betagouv/dora-front pull request #262
Opened 2023-05-17 14:56 UTC by AlexandreCantin

2023-05-23 12:55 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Mise à jour en masse des services (via les modèles)](https://trello.com/c/kBWAkQIa/627-mise-%C3%A0-jour-en-masse-des-services-via-les-mod%C3%A8les)

2023-06-02 14:45 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
> +      window.localStorage.getItem(SERVICE_TO_UPDATE_VIA_MODELS_IGNORED) ?? ""
Je trouve pas la réponse dans les specs, mais tu es sûr que le localStorage suffit? J'aurais plutot pensé qu'on ferait un 'markSynced' sur tous ces services (mais attention, sans les considérer comme à jour, selon un des commentaires de la carte Trello)

2023-06-02 14:45 UTC, cedricr commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
> +      La modale n'étant à l'intérieur de la balise <form />, nous ne pouvons pas utiliser un <input type="submit" />
et on ne peut pas là mettre dans le `<Form>` ?
Après, la classe Form c'est vraiment fait pour encapsuler des champs avec validation, etc. Là pour un checkbox, ça me parait un peu extreme...

2023-06-05 15:59 UTC, AlexandreCantin commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
> +      La modale n'étant à l'intérieur de la balise <form />, nous ne pouvons pas utiliser un <input type="submit" />
J'ai finalement réussi à le faire - mais l'accessibilité de la modale a un peu diminué en conséquence…

2023-06-08 10:50 UTC, cedricr requested changes

2023-06-08 10:50 UTC, cedricr commented on src/lib/requests/services.ts
> +  showModelNotice();
ça m'embete que ça soit là; on melange une requete avec de l'UI; remonte le plutot à l'appellant (et du coup le async sur cette méthode redevient inutile)

2023-06-08 10:50 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
> +  window.localStorage.setItem(MODEL_NOTICE_HIDDEN_KEY, "true");
pourquoi par un vrai booléen?

2023-06-08 10:50 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
> +  window.localStorage.setItem(MODEL_NOTICE_HIDDEN_KEY, "true");
est-ce qu'il ne faut pas indexer ça sur le slug de la structure? Si tu fais partie de plusieurs structures, tu ne veux pas masquer ça pour toutes les structures, ci?

2023-06-08 10:50 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
> +  window.localStorage.setItem(MODEL_NOTICE_HIDDEN_KEY, "true");
et je ne suis pas sûr de comprendre la logique ici; si je lis bien, on va réafficher cette notice quand un modèle est édité; pourquoi ça? Et surtout c'est pas les mêmes personnes qui éditent le modèle et qui ont caché la notice?

Je ne sais pas ce qui est dit dans les specs pour reafficher la notice, mais à mon avis, soit il faut faire un truc restreint dans le temps (on masque pour une semaine par ex.), c'est le plus simple. Soit quand tu masques, tu stockes en localStorage le sync_checksum correspondant pour chaque modele. Quand le sync_checkum change, tu reaffiches la notice, mais seulement pour les modèles dont le sync_checksum a changé.
A discuter avec le metier, je pense que la version 7 jours peut suffir pour commencer.

2023-06-08 10:50 UTC, cedricr commented on src/routes/structures/[slug]/services/list.svelte
> +{#if hasOptions}
Il faudra qu'on renomme ce hasOptions, c'est complètement opaque...

2023-06-08 10:50 UTC, cedricr commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
> +  let updateAllServices = false;
```suggestion
  let shouldUpdateAllServices = false;
```

2023-06-08 10:50 UTC, cedricr commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
Je ne comprends pas toute la complexité ici;

tu as besoin d'une case à cocher, que tu peux binder sur une variable, et d'un bouton qui va déclencher une requete au onClick; pas besoin de <form>, encore moins de <Form> et donc pas besoin de modifier le code de la modale non plus

2023-06-08 13:33 UTC, AlexandreCantin commented on src/lib/utils/service-updates-via-model.ts
> +  window.localStorage.setItem(MODEL_NOTICE_HIDDEN_KEY, "true");
Pour ma part, je comptais masquer la modale jusqu'à ce qu'on créait-modifie un modèle (en gros, elle réapparaît dès qu'on touche un modèle). Et aucune spec, Andrei a parlé de 24h mais je trouve le délai beaucoup trop court 🤔

Par contre, pour le booléen et les multi-structures, en effet, c'est un effet de bord que j'ai complètement zappé… 😓

Je vais modifier pour le localStorage pour partitionner les fenêtres :)
Pour le retour de la fenêtre, je me note d'en discuter lundi :)

2023-06-08 20:27 UTC, cedricr commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
zut, j'avais écrit `<form>` et `<Form>` dans mon commentaire sans les echapper, du coup ils étaient invisibles et tu es (forcement)  passé à coté de ce que je voulais dire... À moins que je rate un truc, tu n'as pas besoin d'un formulaire ici.

2023-06-12 10:05 UTC, AlexandreCantin commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
pas besoin de `<form>` dans la modale
mais il faut quand même que je valide le formulaire de mise à jour du model d'une manière ou une autre :)

2023-06-12 15:46 UTC, cedricr approved these changes
Modulo la question du ??, j'ai pas testé mais ça m'a l'air bon!

2023-06-12 15:46 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
> +  const data = window.localStorage.getItem(MODEL_NOTICES_HIDDEN_KEY) ?? "[]";
le ?? posait pas problème pour les vieilles versions des navigateurs?

2023-06-12 15:46 UTC, cedricr commented on src/routes/(modeles-services)/modeles/model-edition-form.svelte
ahhh je viens de comprendre ok ;-)

2023-06-12 15:46 UTC, cedricr commented on src/lib/utils/service-updates-via-model.ts
ok, t'es allé plus loin que ce que j'imaginais du coup; l'idée des 7 jours c'était de pas se prendre là tête avec un modèle ou l'autre; on cachait la boite et c'est tout; mais maintenant que tu l'as fait...

2023-06-13 07:10 UTC, AlexandreCantin commented on src/lib/utils/service-updates-via-model.ts
> +  const data = window.localStorage.getItem(MODEL_NOTICES_HIDDEN_KEY) ?? "[]";
J'ai revérfié - et non, c'était les `&&=` et `randomUUID()` qui posait problèmes :) 
(les `?.` et les `??`, c'est si jamais on veut descendre encore plus bas au niveau de compatibilité)

Cf : https://trello.com/c/8l6pVCph/662-des-utilisateurs-avec-une-vieille-version-de-firefox-ou-chrome-ne-peuvent-pas-s%CC%B5e%CC%B5-c%CC%B5o%CC%B5n%CC%B5n%CC%B5e%CC%B5c%CC%B5t%CC%B5e%CC%B5r%CC%B5-utiliser-dora

2023-06-13 07:13 UTC, merged