Orientation answer form
betagouv/dora-front pull request #292
Opened 2023-07-06 07:35 UTC by AlexandreCantin

2023-07-06 12:47 UTC, cedricr requested changes

2023-07-06 12:47 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      {sendOrientation.emailSubject}
@AlexandreCantin non, c'est à hardcoder

2023-07-06 17:33 UTC, cedricr requested changes

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +              Service concernée :<br />
```suggestion
              Service concerné&nbsp;:<br />
```

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                >{sendOrientation.service?.name}</span
Hmmm l'objet orientation a forcement un service, sauf si on supprime ce service... mais si c'est le cas, il vaut mieux marquer "Service supprimé" ou qqchose dans ce genre... Tu vois avec Andrei?

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                >{sendOrientation.service?.name}</span
Je *pense* aussi que ça devrait être cliquable, mais c'est pas clair dans la maquette; j'ai posé la question sur Figma

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                        "other"
```suggestion
                        "autre"
```

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                        "other"
ça devrait sans doute être typé qqpart pour éviter les erreurs

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      sendOrientation.beneficiaryAvailability
ça peut être null il me semble

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                        {beneficiarySituation}
ne pas oublier le cas Autre

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                    <strong>Nouvelle demande d'orientation reçue</strong>
il te manque le &nbsp; fermant, mais si tu mets des espaces après, ils ne te servent pas à grand chose ;-)

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                  {#if sendOrientation.service?.contactOtherMethod}
ah non ça existe pas ça...

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                  {#if sendOrientation.service?.contactName}
il faut tester si tu as au moins une des trois infos avant d'afficher cette partie

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                  {#if sendOrientation.service?.contactName}
... mais tu affiches pas les bonnes info. c'est sendOrientation.prescriber.firstName, etc. qu'il te faudrait (la personne qui a rempli la demande d'orientation), mais le back ne te le renvoie pas pour l'instant, je vais l'ajouter

Là tu affiches les infos de contact du service (donc a priori de la personne qui est en train de lire la page)

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                    icon={homeSmile2Icon}
et du coup je pense que c'est sa structure qu'on va vouloir ici.

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      text={sendOrientation.referentEmail}
des mailto: ça serait pas mal

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      text={formatPhoneNumber(sendOrientation.referentPhone)}
href="tel:...", non ?

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +            <hr class="border border-gray-02" />
je pense que ce n'est à afficher que si conseiller.email != prescripteur.email

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
> +<Modal bind:isOpen on:close$ title="Accepter la demande" overflow>
Je vois "Valider la demande" dans les maquettes il me semble

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
> +    {sendOrientation.referentLastName} pour le service «
Les &nbsp;, le » fermant, etc.

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
![image](https://github.com/betagouv/dora-front/assets/7826756/b8aeeff2-ee97-4cdb-81f9-277cb43928f0)

il faut un max-width sur la modale, et du padding à gauche de la scrollbar. L'espace vertical est très mal utilisé aussi.
Pas convaincu par l'usage d'une modale sur un formulaire aussi complexe... J'ai posé la question sur Figma

2023-07-06 17:33 UTC, cedricr commented on src/routes/orientation/[id]/types.ts
> +  id: string;
```suggestion
  orientationId: string;
```

2023-07-10 11:10 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                  {#if sendOrientation.service?.contactName}
Je viens d'ajouter les infos au serialiseur: prescriber.name, prescriber.email

2023-07-10 13:07 UTC, AlexandreCantin commented on src/lib/components/display/breadcrumb.svelte
> +        <a href="/" title="Retour à l‘accueil du site">Accueil</a>
Alors en effet, j'utilise "Opt+4" pour faire le `‘` et il faudrait que j'utilise le `Opt+Shift+4` pour faire `’`
Je me note ça :)

2023-07-10 14:51 UTC, AlexandreCantin commented on src/routes/orientation/[id]/+page.svelte
> +    console.log("update page");
Un relicat d'un test 😅

2023-07-10 15:01 UTC, AlexandreCantin commented on tailwind.config.cjs
> +        "information-dark": "#0762c8",
Pas forcément d'avis mais autant rester constant :)

2023-07-10 16:07 UTC, AlexandreCantin commented on src/routes/orientation/[id]/types.ts
> +  id: string;
Je ne suis pas fait du `orientationId` qui nous donnerait dans le code `orientation. orientationId` et j'ai opté pour le `queryId` au final

2023-07-11 11:51 UTC, AlexandreCantin commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
> +        (séparées par un espace si plusieurs). Format attendu :
Plus de champs… Plus de validation… Plus de problèmes 😅
Sinon, je comptais déléguer la vérification au back - mais c'est vrai que ça pourrait être plus convivial de commencer en front :)

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      >&nbsp;Nouvelle demande d'orientation reçue</strong
en vrai c'est "[DORA] : Nouvelle demande d'orientation reçue", mais je ne sais pas si on va garder le [DORA], je demande.

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                  Service supprimé
Ok pour l'instant, mais je vais serialiser le nom du service, même s'il a été supprimé, pour l'afficher dans tous les cas; il ne sera juste plus cliquable

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                      >&nbsp;Nouvelle demande d'orientation reçue</strong
ok, vu avec Aurelie, on garde, donc tu peux l'ajouter

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                        text={orientation.structure?.name}
ça a été renommé en back pour plus de clarté; c'est orientation.prescriber_structure

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
> +    {sendOrientation.referentLastName} pour le service «
pas fait (à ta décharge, le \&nbsp; n'était pas visible dans le commentaire ;-)

2023-07-11 13:19 UTC, cedricr commented on src/routes/orientation/[id]/accept-orientation-modal.svelte
> +        (séparées par un espace si plusieurs). Format attendu :
en fait tous les gens qui font ça bien (genre les webmail) gèrent ça de façon assez compliquée, et même comme ça c'est souvent difficile...

2023-07-11 13:21 UTC, cedricr commented on src/routes/orientation/[id]/types.ts
> +  id: string;
oui orientationId c'est le vieux nom du queryId, avant qu'on aie aussi un id different ;-)

2023-07-11 14:32 UTC, cedricr requested changes

2023-07-11 14:32 UTC, cedricr commented on src/routes/orientation/[id]/contact-beneficiary-modal.svelte
> +    {orientation.referentLastName}, pour le service «
manquent les \&nbsp; Tu peux faire une passe de vérification sur '« ' et ' »'

2023-07-11 14:32 UTC, cedricr commented on src/routes/orientation/[id]/+page.svelte
> +                        text={orientation.structure?.name}
ça va venir ;-)

2023-07-11 15:03 UTC, AlexandreCantin commented on src/routes/orientation/[id]/+page.svelte
> +      {formatNumericDate(orientation.creationDate)}
j'ai créé la fonction… que je n'ai pas utilisé 😓

2023-07-11 15:20 UTC, AlexandreCantin commented on src/lib/utils/orientation.ts
en effet, la fonction de `handleSubmit` de `<Form />` attend un `{"ok": true }` :)

2023-07-11 15:41 UTC, cedricr requested changes

2023-07-11 15:50 UTC, AlexandreCantin commented on src/routes/orientation/[id]/+page.svelte
> +                      >[DORA]&nbsp;: Nouvelle demande d'orientation reçue</strong
Je l'avais déjà pris en compte et n'avais pas revert…

2023-07-11 16:27 UTC, cedricr submitted a review, later dismissed

2023-07-11 16:32 UTC, merged