Validation des CGU
betagouv/dora-front pull request #310
Opened 2023-07-25 09:16 UTC by AlexandreCantin

https://trello.com/c/3qZTwWcb/781-validation-des-nouvelles-cgu-pour-les-anciens-inscrits

2023-07-25 09:18 UTC, AlexandreCantin commented
![](https://github.trello.services/images/mini-trello-icon.png) [Validation des nouvelles CGU pour les anciens inscrits](https://trello.com/c/3qZTwWcb/781-validation-des-nouvelles-cgu-pour-les-anciens-inscrits)

2023-07-25 16:55 UTC, cedricr requested changes

2023-07-29 17:40 UTC, cedricr requested changes

2023-07-29 17:40 UTC, cedricr commented on .env-example
> +VITE_CGU_VERSION=
Non; c'est pas qq chose qu'on définit dans l'environnement; je verrais plutot ça dans un fichier version.ts dans /(static)/cgu

2023-07-29 17:40 UTC, cedricr commented on src/lib/utils/auth.ts
> +  cgu: Record<string, string>;
cguVersionsAccepted

2023-07-29 17:40 UTC, cedricr commented on src/routes/auth/rattachement/+page.svelte
> +            {:else}
Pour ces differentes branches du code penser à prévenir les testeur·euses pour que tous les cas soient vérifiés

2023-07-29 17:40 UTC, cedricr commented on src/routes/+layout.ts
> +    // Si l'utilisateur a besoin de valider les CGU en cours de validité
Pour ces differentes branches du code penser à prévenir les testeur·euses pour que tous les cas soient vérifiés

2023-08-07 09:26 UTC, AlexandreCantin commented on src/routes/+layout.ts
> +    // Si l'utilisateur a besoin de valider les CGU en cours de validité
En effet, je compte faire un petit guide à Andrei pour les tests :)

2023-08-07 09:26 UTC, AlexandreCantin commented on src/routes/auth/rattachement/+page.svelte
> +            {:else}
En effet, je compte faire un petit guide à Andrei pour les tests :)

2023-08-07 12:32 UTC, cedricr submitted a review, later dismissed

2023-08-08 12:12 UTC, cedricr submitted a review, later dismissed

2023-08-08 14:01 UTC, merged