feat(recherche de service): ajoute des filtres
betagouv/dora-front pull request #32
Opened 2022-03-02 10:29 UTC by francoisromain

2022-03-03 11:32 UTC, cedricr requested changes

2022-03-03 11:32 UTC, cedricr commented on src/routes/recherche.svelte
> +    const hasNoFees = query.get("has_fees") === "0";
le backend attend `has_fee` sans s

2022-03-03 11:32 UTC, cedricr commented on src/routes/_homepage/_search.js
> +    parameters.has_fees = "0";
le backend attend `has_fee` sans s

2022-03-05 14:53 UTC, cedricr commented on src/lib/components/newsletter-button.svelte
> +  label="S'abonner à la newsletter"
```suggestion
  label="S’abonner à la newsletter"
```

2022-03-05 14:53 UTC, cedricr commented on src/routes/_homepage/_search_tweak_form.svelte
> +  <form on:submit|preventDefault={handleSearch} class="flex flex-col gap-s16">
Pourquoi le collapsable a disparu? C'est une demande d'Andrei? C'était pas mal sur telephone…

2022-03-05 14:53 UTC, cedricr commented on src/routes/recherche.svelte
> +  <title>Services d'insertion | Recherche | DORA</title>
Interessant de mettre les tags dedans peut-être? Tu en penses quoi?

2022-03-07 09:02 UTC, francoisromain commented on src/routes/_homepage/_search_tweak_form.svelte
> +  <form on:submit|preventDefault={handleSearch} class="flex flex-col gap-s16">
Il n'est pas dans la maquette. Et j'essaie d'uniformiser les composants et les styles. Si tu y tiens, on peut rajouter l'otpion `collapsable` sur fieldset

2022-03-07 11:16 UTC, cedricr commented on src/routes/_homepage/_search_tweak_form.svelte
> +  <form on:submit|preventDefault={handleSearch} class="flex flex-col gap-s16">
Si, il est sur la maquette responsive, et ça me parait super important quand tu fais une recherche sur téléphone, sinon au lieu de voir des resultats, tu restes sur le même formulaire
https://www.figma.com/proto/8JAD0LV2TkjEOpomcrA6dX/DORA---MLP?page-id=1864%3A17304&node-id=1872%3A17843&viewport=241%2C48%2C0.79&scaling=min-zoom&starting-point-node-id=1872%3A17361&show-proto-sidebar=1

2022-03-07 16:56 UTC, francoisromain commented
et paf! ça collapse

2022-03-07 17:09 UTC, cedricr approved these changes
Top. Les tags dans le titre ça marche mal je trouve (titre trop long), il faudra peut-etre mieux les mettre dans la description meta… mais on verra ça plus tard!

2022-03-08 08:47 UTC, merged