feat: deplace le tableau de bord sur la page de structure
betagouv/dora-front pull request #39
Opened 2022-03-17 07:39 UTC by francoisromain

2022-03-19 18:03 UTC, cedricr requested changes

2022-03-21 13:36 UTC, cedricr commented on src/routes/structures/[slug]/_header.svelte
> +  if (structure.canWrite) {
non les bizdevs n'ont pas canWrite, mais peuvent voir les collaborateurs

2022-03-21 19:51 UTC, francoisromain commented on tailwind.config.cjs
> -    screens: {
ça n'est utile que pour utiliser l'instruction `print:` directement dans un style https://v2.tailwindcss.com/docs/breakpoints#styling-for-print. Il n'y en a pas dans l'appli. 

Par contre j'ai bien introduit un bug sur la css print. Je le corrige.

2022-03-21 20:14 UTC, cedricr commented on src/routes/auth/mdp-perdu.svelte
>        description="Saisissez l’adresse email que vous avez utilisé lors de l’inscription."
courriel

2022-03-21 20:14 UTC, cedricr commented on src/routes/mon-compte/_form-informations.svelte
> +      placeholder="nom@domaine.tld"
ou @exemple.com

2022-03-21 20:16 UTC, cedricr commented on src/routes/services/form/_step4.svelte
> +        placeholder="1 rue exemple"
un nom de rue plausible c'est plus joli ;-)

2022-03-21 20:16 UTC, cedricr commented on src/routes/services/form/_step4.svelte
> +      placeholder="00000"
J'aime mieux les 'vrais' numéros, mais pourquoi pas

2022-03-21 23:18 UTC, francoisromain commented on src/routes/tableau-de-bord/index.svelte
> -      {#if pendingStructures.length}
@cedricr du coup est ce que tu peux les exposer dans `userInfo` ?

2022-03-21 23:23 UTC, francoisromain commented on src/routes/tableau-de-bord/index.svelte
> -      {#if pendingStructures.length}
idéalement ça serait une propriété `pending` sur la structure qui serait dans lla même liste que les autres.

2022-03-22 07:50 UTC, francoisromain commented on src/routes/mon-compte/_notif-improve.svelte
> +    label="Participer (3min.)…"
En attente de la réaction d'Andrei

2022-03-22 07:52 UTC, francoisromain commented on src/lib/components/services/line.svelte
> +<div class="flex flex-row gap-s16 rounded-md bg-white p-s16">
J'ai passé le nom du service et de la structure dans la même cellule pour éviter les nombreux retours à la ligne

2022-03-22 08:09 UTC, francoisromain commented on src/routes/mon-compte/_notif-improve.svelte
> +    label="Participer (3min.)…"
vu par Andrei

2022-03-22 08:10 UTC, francoisromain commented
J'ai tout corrigé sauf les `pendingStructures`. Cela demande une intervention côté backend.

2022-03-22 10:37 UTC, cedricr requested changes

2022-03-22 10:37 UTC, cedricr commented on src/routes/services/creer.svelte
> +      structures = await user.structures;
je pense que le await serait plus ligne 9, 
const user = await get(userInfo)

2022-03-22 11:02 UTC, cedricr approved these changes
🎉

2022-03-22 11:47 UTC, merged