feat(feedback): ajout des formulaires de retours utilisateurs + tracking du temps de complétion
betagouv/dora-front pull request #68
Opened 2022-07-11 08:41 UTC by AlexandreCantin

2022-07-12 13:26 UTC, cedricr commented on src/routes/services/[slug]/_feedback-modal.svelte
> +<Modal title="Donnez votre avis" isOpen on:close={() => formTrackStore.clear()}>
bind:isOpen={xxx} plutôt ? Voir mon commentaire sur src/routes/services/[slug]/index.svelte

2022-07-12 13:41 UTC, cedricr commented on src/lib/components/modal.svelte
> +    dispatch("close");
Attention ça ne va être dispatché que quand on clique sur le bouton pour fermer la modale, pas on clique en fond d'écran, etc.

2022-07-12 15:30 UTC, AlexandreCantin commented on package.json
> +    "lodash": "^4.17.21",
Pour moi, le tree-shaking est fait correctement par `lodash` => toutefois, j'ai opté pour `https://www.npmjs.com/package/lodash.debounce` pour s'en assurer :)

2022-07-12 15:34 UTC, AlexandreCantin commented on src/lib/components/modal.svelte
> +        <h1 class="h2">{title}</h1>
Pour l'accessibilité, il faut que la modale commence par un h1 :)
Malheureusement, on se retrouve avec un design complètement différent.. corriger avec une classe CSS

Mais c'est vrai que c'est confusant, je vais réfléchir à avoir un nom différent que `h2` 👍

2022-07-12 15:38 UTC, AlexandreCantin commented on src/lib/stores/form-track.ts
> +import type { Writable } from "svelte/store";
J'avoue entretenir le projet de migrer la codebase petit à petit en TS - et ceci en est la première pierre :)

2022-07-12 16:10 UTC, AlexandreCantin commented on src/routes/contribuer/form/_form-wrapper.svelte
> +  on:mousemove={updateLastUserActivity}
J'ai testé avec les outils de debug de Chrome et il déclenche un `mousemove` en cas de `touch`... J'avoue que j'y crois moyen... 😅
J'ajoute une note sur Notion pour qu'on pense à regarder ce cas

2022-07-13 07:43 UTC, AlexandreCantin commented on src/routes/services/[slug]/index.svelte
> +  {#if showFeedbackModal}
Du coup, c'est géré par un `bind:open` 🙂

2022-07-13 09:45 UTC, cedricr commented on src/lib/components/modal.svelte
> +        <h1 class="h2">{title}</h1>
C'est uniquement utilisé dans la modale, met directement le style inline, non?

2022-07-13 09:51 UTC, cedricr commented on src/lib/stores/form-track.ts
> +import type { Writable } from "svelte/store";
Alors je suis à fond pour, mais c'est le genre de grosses décisions dont il vaut mieux qu'on prenne 5 minutes pour en discuter de vive voix ;)
Il n'y a rien de plus à faire coté tooling ? Dans ce (vieil) article, ça avait l'air un peu plus complexe: https://svelte.dev/blog/svelte-and-typescript

2022-07-13 09:55 UTC, cedricr commented on src/routes/contribuer/form/_form-wrapper.svelte
> +  on:mousemove={updateLastUserActivity}
Je t'ai répondu dans Notion, mais si ce n'est pas simple ça peut venir plus tard, il faut juste qu'on le note (dans "Dette technique" peut-etre?)

2022-07-13 10:04 UTC, cedricr requested changes
Voir discussion globale sur le style inline, et vérifier le tooling TS

2022-07-13 11:02 UTC, AlexandreCantin commented on src/lib/stores/form-track.ts
> +import type { Writable } from "svelte/store";
Avec Svelte-kit, Typescript est déjà inclus - je n'ai rien eu à faire niveau tooling :)
Et pas de soucis pour en discuter, je vais faire un fallback en JS en attendant 🙂

2022-07-13 11:03 UTC, AlexandreCantin commented on src/routes/contribuer/form/_form-wrapper.svelte
> +  on:mousemove={updateLastUserActivity}
J'ai suivi le lien et modifier l'option mais je n'ai constaté aucun changement 🤷‍♂️

2022-07-13 11:58 UTC, cedricr approved these changes

2022-07-13 12:00 UTC, merged