feat(nps): ajout formulaire NPS
betagouv/dora-front pull request #69
Opened 2022-07-11 14:57 UTC by AlexandreCantin

Ajout du formulaire de NPS (`embed.js` via Tally)

2022-07-12 12:56 UTC, cedricr requested changes
Bien en l'état, à part le bug sur l'unmount; par contre ça me parait trop intrusif — j'ai mis un commentaire sur la carte Notion pour faire préciser ça

2022-07-12 12:56 UTC, cedricr commented on src/routes/recherche.svelte
> +  import TallyNpsPopup from "$lib/components/tally-nps-popup.svelte";
TallyNPSPopup ? Bof comme toujours avec les sigles, les deux sont moches; je ne suis pas sûr qu'on ait déjà des exemples dans le code, il faudrait juste qu'on se mette d'accord et qu'on soit consistent… Je te laisse choisir!

2022-07-12 12:56 UTC, cedricr commented on src/routes/recherche.svelte
> +<TallyNpsPopup formId="3xXVJ5" />
Etant donné que l'id est utilisé deux fois, je le mettrais bien dans $lib/env.js (sans forcement le connecter aux variables d'environnement, mais juste pour en faire une constante)

2022-07-12 14:48 UTC, AlexandreCantin commented on src/routes/recherche.svelte
> +  import TallyNpsPopup from "$lib/components/tally-nps-popup.svelte";
Je vais voter pour `TallyNpsPopup` en espérant que je ne le regretterai pas un jour 😅

2022-07-12 14:51 UTC, AlexandreCantin commented on src/routes/recherche.svelte
> +<TallyNpsPopup formId="3xXVJ5" />
J'ai plus opté pour un `$lib/const.js` qui me semblait plus pertinent :)

2022-07-12 15:01 UTC, cedricr approved these changes
Gros doute sur le moment où on fait le localStorage.setItem, mais à voir avec le metier! Pour le reste c'est bon pour moi.

2022-07-12 15:01 UTC, cedricr commented on src/lib/components/tally-nps-popup.svelte
> +          localStorage.setItem(localStorageKey, "1");
Ouais pas mal, mais si tu n'as pas envie de repondre, tu vas fermer la modale, et on va la réouvrir juste après… je pense qu'il faut faire le setItem en même temps que le openPopup, mais n'hésites pas à en discuter dans le ticket Notion,

2022-07-12 15:16 UTC, AlexandreCantin commented on src/lib/components/tally-nps-popup.svelte
> +          localStorage.setItem(localStorageKey, "1");
Je me suis basé sur les paroles d'Andrei : 
```
- on ne l’affiche pas si l’on est le "contributeur" du service 
- si on a déjà répondu 
```
mais je demande confirmation au cas où :)

2022-07-13 12:21 UTC, AlexandreCantin commented on src/lib/components/tally-nps-popup.svelte
> +          localStorage.setItem(localStorageKey, "1");
on assume de forcer un peu la main 😉 => on adaptera plus tard si le besoin se fait sentir

2022-07-13 12:21 UTC, merged