Mails automatiques après validation d'une contribution
betagouv/dora-front pull request #78
Opened 2022-07-25 13:42 UTC by AlexandreCantin

2022-07-26 11:42 UTC, cedricr requested changes

2022-07-26 11:42 UTC, cedricr commented on src/routes/services-suggestions/_list.svelte
> +        Toutefois, aucun courriel n'a été envoyé car aucun destinataire n'a pu
’ au lieu de '
… au lieu de ...

2022-07-26 11:42 UTC, cedricr commented on src/routes/services-suggestions/_list.svelte
> +        La ou les personnes suivantes ont reçus un courriel les invitant à
```suggestion
        La ou les personnes suivantes ont reçu un courriel les invitant à
```

2022-07-26 11:42 UTC, cedricr commented on src/routes/services-suggestions/_list.svelte
> +        prendre connaissance de ce nouveau service :
```suggestion
        prendre connaissance de ce nouveau service&nbsp;:
```

2022-07-26 11:42 UTC, cedricr commented on src/lib/services.js
> +      result.body = await res.json();
on utilise plutot result.data pour ça dans le reste du fichier; il faudra faire une grande unification un de ces jours!

2022-07-26 15:39 UTC, cedricr commented on src/routes/contribuer/form/_form-wrapper.svelte
> +              result.data.serviceInfo?.structureInfo?.siret || "aucun-siret"
Hum dans quel cas ça? Normalement sans siret on ne peut pas publier

2022-07-26 15:39 UTC, cedricr approved these changes

2022-07-27 08:52 UTC, AlexandreCantin commented on src/routes/contribuer/form/_form-wrapper.svelte
> +              result.data.serviceInfo?.structureInfo?.siret || "aucun-siret"
En local, il s'avère que j'ai le `serviceInfo` de vide

```json
{
    "id": "efd38b72-xxx,
    "name": "test_ALEX",
    "siret": "44xxxxx",
    "structureInfo": {
        "name": "DAOUDAL ANNE",
        "department": "44",
        "new": true
    },
    "creator": {
        "getFullName": "AlexandreC",
        "email": "example@example.com"
    },
    "serviceInfo": {}
}
```

2022-07-27 21:02 UTC, cedricr commented on src/routes/contribuer/form/_form-wrapper.svelte
> +              result.data.serviceInfo?.structureInfo?.siret || "aucun-siret"
ok, je vais vérifier ça, mais tu peux merger en attendant

2022-07-28 06:52 UTC, merged

2022-07-28 09:22 UTC, cedricr commented on src/routes/contribuer/form/_form-wrapper.svelte
> +              result.data.serviceInfo?.structureInfo?.siret || "aucun-siret"
alors, déjà, utilises result.data.siret au lieu de result.data.serviceInfo?.structureInfo?.siret 😅
Et je regarde pourquoi le serviceInfo est vide

2022-07-28 09:28 UTC, cedricr commented on src/routes/contribuer/form/_form-wrapper.svelte
> +              result.data.serviceInfo?.structureInfo?.siret || "aucun-siret"
ok j'arrive pas à reproduire, il est bien rempli chez moi; d'après le code, il pourrait être vide en cas d'erreur de parsing de la suggestion.
https://github.com/betagouv/dora-back/blob/liste-choix/dora/service_suggestions/serializers.py#L53
Je veux bien que tu essayes de reproduire à l'occasion!