Add radius to the search form
betagouv/dora-front pull request #8
Opened 2022-01-05 17:09 UTC by francoisromain

2022-01-05 17:09 UTC, francoisromain commented on src/routes/recherche.svelte
> +    const radius = query.get("ra") || "10";
j'ai un doute sur la bonne façon d'initialiser la valeur de radius

2022-01-06 13:59 UTC, cedricr requested changes

2022-01-06 13:59 UTC, cedricr commented on src/routes/_homepage/_search.js
> +    .join("&");
👍

2022-01-06 13:59 UTC, cedricr commented on src/routes/recherche.svelte
> +      null,
Moi je changerais plutot l'ordre des parametres pour mettre le cityLabel en dernier, et éviter ce null au milieu.

2022-01-06 13:59 UTC, cedricr commented on src/routes/recherche.svelte
> +    const radius = query.get("ra") || "10";
```suggestion
    const radius = query.get("radius") || "10";
```

2022-01-06 13:59 UTC, cedricr commented on src/routes/recherche.svelte
> +    const radius = query.get("ra") || "10";
Pourquoi tu as besoin d'une valeur par defaut? Le parametre doit être présent a priori, comme pour les autres champs non?

2022-01-06 13:59 UTC, cedricr commented on src/routes/_homepage/_search.js
> +    ra: radius,
```suggestion
    radius,
```

Attention, l'API attend `radius`, pas `ra`.
(Ce qui est un peu crad, c'est que j'utilisais la même méthode pour préparer les parametres de l'appel back que pour la page en front.)

2022-01-06 14:06 UTC, francoisromain commented on src/routes/recherche.svelte
> +      null,
ok je change

2022-01-06 14:28 UTC, francoisromain commented on src/routes/recherche.svelte
> +    const radius = query.get("ra") || "10";
si on fait un accès direct à la page depuis une url bookmarké par exemple, le paramètre ne sera pas dans l'url.

2022-01-06 14:34 UTC, cedricr commented on src/routes/recherche.svelte
> +    const radius = query.get("ra") || "10";
Hum, c'est vrai que les autres parametres sont vides par defaut, alors que celui là a une valeur par defaut.
Dans ce cas j'essayerais plutot de faire comme tu l'as fait dans _search-form.js, un truc du genre
radiusChoices[0].value.

Et un jour, il faudra qu'on factorise un peu mieux ces deux fichiers.

2022-01-10 11:22 UTC, cedricr approved these changes

2022-01-10 11:22 UTC, merged