feat: formulaire de feedback uniquement lors de la première publication d'un service
betagouv/dora-front pull request #81
Opened 2022-07-28 14:15 UTC by AlexandreCantin

Ticket notion : https://www.notion.so/dora-beta/34b8d00134874128a1a2fa1e896ebe8b?v=983392aa02e64036b5d6ebc915a16f33&p=a61c95ff19ae43e2901c4d0e869bb2ba&pm=s

2022-08-01 10:17 UTC, cedricr requested changes

2022-08-01 10:17 UTC, cedricr commented on src/routes/services/[slug]/index.svelte
> +  {#if $serviceSubmissionTimeMeter.id && $serviceSubmissionTimeMeter.duration && isAfter(new Date(service.creationDate), MIN_DATE_FOR_SERVICE_FEEDBACK_FROM) && service.has_already_been_unpublished}
Même remarque que dans l'autre PR, je pense qu'on ne lit pas "has_already_been_unpublished" dans le même sens:

"has_already_been_unpublished" ça veut dire qu'il a déjà été publié et qu'il est en brouillon pour la seconde fois; et dans ce cas, on ne veut pas afficher le formulaire.

2022-08-01 16:42 UTC, AlexandreCantin commented on src/routes/services/[slug]/index.svelte
> +  {#if $serviceSubmissionTimeMeter.id && $serviceSubmissionTimeMeter.duration && isAfter(new Date(service.creationDate), MIN_DATE_FOR_SERVICE_FEEDBACK_FROM) && service.has_already_been_unpublished}
Pour moi `service.has_already_been_unpublished` signifie que le service est passé par le status `PUBLISHED => X` une fois dans sa vie
Si c'est le cas, le formulaire Tally ne doit pas s'afficher...

2022-08-01 16:45 UTC, cedricr commented on src/routes/services/[slug]/index.svelte
> +  {#if $serviceSubmissionTimeMeter.id && $serviceSubmissionTimeMeter.duration && isAfter(new Date(service.creationDate), MIN_DATE_FOR_SERVICE_FEEDBACK_FROM) && service.has_already_been_unpublished}
ben oui on est d'accord… mais là tu as if(service.has_already_been_unpublished) => afficher tally, non? J'ai raté un truc?

2022-08-02 10:28 UTC, AlexandreCantin commented on src/routes/services/[slug]/index.svelte
> +  {#if $serviceSubmissionTimeMeter.id && $serviceSubmissionTimeMeter.duration && isAfter(new Date(service.creationDate), MIN_DATE_FOR_SERVICE_FEEDBACK_FROM) && service.has_already_been_unpublished}
... comme indiqué côté back, il semblerait que je me sois perdu dans mon renommage 🥲

2022-08-02 10:29 UTC, cedricr approved these changes
Validé, mais on la garde en draft jusqu'à la MEP

2022-08-03 13:05 UTC, merged