Feat/refacto service header
betagouv/dora-front pull request #91
Opened 2022-08-10 16:22 UTC by AlexandreCantin

2022-08-15 20:46 UTC, cedricr requested changes
Top comme d'hab, malgré pas mal de petites remarques. A revoir en particulier, l'utilisation des icones, et quelques nommages de fichiers qui me paraissent peu clairs.
Je n'ai pas du tout relu les test pour l'instant par contre!

2022-08-15 20:46 UTC, cedricr commented on src/lib/types.ts
> +  shortDesc: string | undefined;
En fait les services sont soit renvoyés sous forme de liste, avec peu de champs, soit un par un, avec l'intégralité des champs. 
Je pense que ça mériterait deux types differents.
Même chose pour les structures.
(et ça peut être pour une autre fois)

2022-08-15 20:46 UTC, cedricr commented on src/lib/utils/service/index.ts
> +import ArchivedIcon from "$lib/assets/services/status/service-archived.svg";
Voir commentaire plus haut sur la gestion des icones

2022-08-15 20:46 UTC, cedricr commented on src/lib/utils/service/index.ts
> +type ServiceUpdateStatusData = {
Il y a un mélange de présentation et de modèle ici qui me dérange un peu. Tu as le 'label', qui te permet de faire de l'affichage, ailleurs, tu vas afficher le 'monthDiff' dans les messages, et les autres diff sont, je crois, utilisés seulement pour les tests…
Je garderais uniquement la date et le statut, et là où tu as besoin de récupérer tes diverses 'diff' et labels/messages, tu pourrais les recalculer, ou appeler une méthode utilitaire qui le ferait.

2022-08-15 20:46 UTC, cedricr commented on src/routes/services/[slug]/index.svelte
> +  import ServiceUpdateToolbar from "$lib/components/services/service-update-toolbar.svelte";
Pas sûr de comprendre ce "Update" qui est apparu un peu partout… C'est pour 'Actualisation' c'est ça? Mais il n'y a pas que les infos d'actualisation dans ces fichiers là si?

2022-08-15 20:46 UTC, cedricr commented on src/routes/services/[slug]/index.svelte
> +  <div class="noprint">
Il faut que je te montre comment tester les PDFs…

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-state-update-select.svelte
> +<script lang="ts">
Composant génial, mais je pense qu'il faudrait le décomposer entre un combobox générique et le composant lui-même.
Ça peut aussi être fait plus tard, la première fois qu'on aura besoin d'un autre combobox…

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-status-as-user.svelte
> +<script lang="ts">
le nom du fichier n'est pas assez clair… à voir pour le 'update', mais 'user' est trop vague, tout le monde est un 'user'. J'imagine que c'est la version "chercheur" vs la version "offreur', mais il faut qu'on trouve mieux ;)
Pour l'instant je lis ça comme "statut de mise à jour du service en tant qu'utilisateur".

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-status-as-writer.svelte
> +<script lang="ts">
Même remarque pour le nom de fichier

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-toolbar.svelte
> +  $: {
pourquoi la réactivité ici?

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-toolbar.svelte
> +  {#if $token && service.canWrite}
service.canWrite implique que tu aies un token je pense; pourquoi le test ici?

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-toolbar.svelte
> +              <img class="mr-s10" src={SynchronizedIcon} alt="" /> Synchronisé avec
remarque habituelle sur les icones
jusqu'à maintenant on utilisait plutot un truc du genre
```
    <div class="mr-s8 h-s24 w-s24 fill-current">
      {@html alertIcon}
    </div>
```

2022-08-15 20:46 UTC, cedricr commented on src/lib/components/services/service-update-toolbar.svelte
> +  .NOT_NEEDED {
classes CSS en majuscule?

2022-08-16 11:29 UTC, AlexandreCantin commented on tailwind.config.cjs
> +      "service-green": { DEFAULT: "#E6F3EC", dark: "#B3DCC6" },
En effet, c'est plus lisible :)

2022-08-16 13:03 UTC, AlexandreCantin commented on src/lib/utils/service/index.ts
> +type ServiceUpdateStatusData = {
J'ai externalisé la fonction de génération du label :)

2022-08-16 13:29 UTC, AlexandreCantin commented on src/lib/components/services/service-update-toolbar.svelte
> +  $: {
Après le `onRefresh` en cas de changement de status, on a bien le `fetch` mais pas de mis à jour du status dans le `select`... D'où la réactivité :)

2022-08-16 13:39 UTC, AlexandreCantin commented on src/lib/components/button.svelte
> +  export let id: string | undefined | null = null;
En mettant, une valeur par défaut, le `| undefined` devient inutile 😅
Et sinon, malheureusement, en mettant `""` comme valeur par défaut, on a un `id` vide...

![Capture d’écran 2022-08-16 à 15 36 01](https://user-images.githubusercontent.com/1846641/184893136-3b856243-4751-42cd-8011-fd49692d8d6e.png)

Je vais retirer le `| null` et ne pas mettre de valeur par défaut - et ça devrait déjà simplifié :)

2022-08-16 13:46 UTC, AlexandreCantin commented on src/lib/components/breadcrumb.svelte
> +        href={CANONICAL_URL}
En effet 😅

2022-08-16 13:47 UTC, AlexandreCantin commented on src/lib/components/services/service-update-toolbar.svelte
> +  .NOT_NEEDED {
J'utilise `class={updateStatus}` dans le component et `updateStatus` provient de cet enum : 

``
`
export enum SERVICE_UPDATE_STATUS {
  NOT_NEEDED = "NOT_NEEDED",
  NEEDED = "NEEDED",
  REQUIRED = "REQUIRED",
}
```

Alors, j'avoue que les majuscules, c'est pas top... Mais pas assez pour ajouter un mapper (`NOT_NEEDED` => `not-needed`) 🤷‍♂️

2022-08-16 13:57 UTC, AlexandreCantin commented on package.json
> +    "dayjs": "^1.11.4",
Etant donné que `dayjs` sert pour déterminer le temps entre aujourd'hui et la dernière mise à jour côté front - c'est une `dependencies` :)

2022-08-16 13:59 UTC, AlexandreCantin commented on package.json
> +    "@sinonjs/fake-timers": "^9.1.2",
En effet, cet import ne servait à rien, bien vu ! 👍

2022-08-16 14:00 UTC, AlexandreCantin commented on src/lib/components/breadcrumb.svelte
> +        ><span class="hidden lg:inline">Structure&nbsp;·&nbsp;</span
Le point médian `•` est beaucoup mieux :)

2022-08-16 14:03 UTC, AlexandreCantin commented on src/lib/utils/service/index.ts
> +export const SERVICE_STATUS_PRESENTATION: Record<
En effet, il serait plus proche de son utilisation (même si ça alourdit un fichier déjà lourd 🥲)

2022-08-16 14:06 UTC, AlexandreCantin commented on src/lib/types.ts
> +export type Service = {
En effet, il faudra étudier cette question... Des librairies doivent exister pour le faire automatiquement... 🤔

2022-08-16 14:22 UTC, AlexandreCantin commented on src/lib/types.ts
> +// eslint considère à tort que les valeurs enum ne sont pas utilisées...
Si j'en crois : https://github.com/typescript-eslint/typescript-eslint/issues/2621
Il faut désactiver la règle eslint et activer la règle typescript

2022-08-16 14:27 UTC, AlexandreCantin commented on src/lib/types.ts
> +  shortDesc: string | undefined;
Oui et d'ailleurs, ça pourrait être pertinent d'utiliser `Pick` à ce moment-là
=> https://www.typescriptlang.org/docs/handbook/utility-types.html#picktype-keys

2022-08-16 14:33 UTC, AlexandreCantin commented on src/lib/types.ts
> +export enum SERVICE_STATUSES {
La seule différence que je connais c'est au niveau de l'import (qui nécessite le préfixe `type`)

2022-08-16 15:45 UTC, AlexandreCantin commented on src/lib/components/services/service-update-status-as-writer.svelte
> +<script lang="ts">
Au final, j'ai opté pour `as-contributor`

2022-08-16 15:51 UTC, AlexandreCantin commented on src/routes/services/[slug]/index.svelte
> +  import ServiceUpdateToolbar from "$lib/components/services/service-update-toolbar.svelte";
J'ai surtout changer pour que le diff Github ne soit pas indigeste... mais le `update` est peut-être mal adapté...
Je vais retourner à `ServiceToolbar` 🙂

2022-08-16 15:52 UTC, AlexandreCantin commented on src/lib/components/services/service-state-update-select.svelte
> +<script lang="ts">
On verra quand le besoin se présentera :)

2022-08-16 15:53 UTC, AlexandreCantin commented on src/lib/components/services/service-update-status-as-writer.svelte
> +<script lang="ts">
Alors j'ai modifié pour `as-contributor` et `as-reader`

2022-08-16 15:55 UTC, AlexandreCantin commented on src/lib/components/services/service-update-toolbar.svelte
> +  {#if $token && service.canWrite}
Je me suis basé sur du code existant 😅 mais si `canWrite` suffit !

2022-08-17 07:32 UTC, AlexandreCantin commented
C'est prêt pour une nouvelle passe @cedricr 🙂

2022-08-17 07:39 UTC, cedricr commented on package.json
> +    "dayjs": "^1.11.4",
C'est pas si simple: avec Vite/Sveltekit, presque tout devrait être en devDependencies, il récupère ce qu'il faut au moment du build, mais ce n'est pas le cas pour toutes les dependences (ex: tiptap). D'où le commentaire plus haut dans le fichier, qui permet de faire la difference. (je n'ai jamais creusé assez le sujet pour comprendre exactement; l'idée c'est de commencer par mettre les nouveaux packages en devDep, de faire tourner la ligne de commande évoquée en commentaire, et de les passer en dep. si nécessaire)

2022-08-17 08:55 UTC, cedricr requested changes

2022-08-17 08:55 UTC, cedricr commented on src/lib/components/button.svelte
> +  export let id: string | undefined | null = null;
hum sans valeur par defaut, ça fait des tonnes de warnings dans la console, mais tu peux mettre la valeur par defaut à undefined.
https://svelte.dev/docs#component-format-script-1-export-creates-a-component-prop
> In development mode (see the [compiler options](https://svelte.dev/docs#compile-time-svelte-compile)), a warning will be printed if no default initial value is provided and the consumer does not specify a value. To squelch this warning, ensure that a default initial value is specified, even if it is undefined.

2022-08-17 08:55 UTC, cedricr commented on src/lib/utils/service/index.ts
> +type ServiceUpdateStatusData = {
ok, toujours pas convaincu par le fait que ServiceUpdateStatusData renvoie tous les *diff, qui à mon avis devraient être calculés par la fonction de génération du label; mais pas horiffié non plus, donc comme tu veux ;-)

2022-08-17 08:55 UTC, cedricr commented on src/lib/components/breadcrumb.svelte
> +  nav li + li::before {
bof au final c'était limite plus clair avant la modif… à toi de voir

2022-08-17 08:55 UTC, cedricr commented on src/lib/components/link-button.svelte
> +  export let id: string | undefined;
Même chose que pour le bouton, je pense qu'il faut un defaut à undefined

2022-08-17 08:55 UTC, cedricr commented on src/lib/components/services/service-update-toolbar.svelte
> +  $: {
ok, mais là je la trouve un peu lourde; tu pourrais laisser tomber les let initiaux et faire juste:

  $: updateStatusData = computeUpdateStatusData(service);
  $: label = computeUpdateStatusLabel(updateStatusData);


et dans le code, utiliser directement updateStatusData.updateStatus, etc.

ou alors, faire les 4 déclarations:
  $: updateStatusData = computeUpdateStatusData(service);
  $:monthDiff = updateStatusData.monthDiff;
  $: updateStatus = updateStatusData.updateStatus;
  $: label = computeUpdateStatusLabel(updateStatusData);

Ça évite d'avoir à la fois une initialisation une maj réactive des variables

2022-08-17 09:15 UTC, AlexandreCantin commented on package.json
> +    "@types/sinonjs__fake-timers": "^8.1.2",
Je l'ai juste oublié...

2022-08-17 09:33 UTC, AlexandreCantin commented on src/lib/components/services/service-update-toolbar.svelte
> +  $: {
J'ai opté pour l'option 1 🙂

2022-08-17 09:44 UTC, AlexandreCantin commented on src/lib/components/breadcrumb.svelte
> +  nav li + li::before {
On va garder l'option tailwind :)

2022-08-17 09:46 UTC, AlexandreCantin commented on src/lib/utils/service/index.ts
> +type ServiceUpdateStatusData = {
En fait, on a besoin du monthDiff à un autre endroit (que dans le label).
Toutefois, je propose qu'on garde comme cela et qu'on voit ensuite à l'usage (et ce ne sera pas un refacto énorme)...

2022-08-17 09:53 UTC, AlexandreCantin commented on package.json
> +    "dayjs": "^1.11.4",
Du coup, après avoir essayé, j'ai bien une erreur avec `dayJs` dans les devDependencies 
`Error [ERR_MODULE_NOT_FOUND]: Cannot find package 'dayjs' imported from /Users/alexandre-cantin/Desktop/dora-front/build/server/entries/pages/services/_slug_/index.svelte.js`

2022-08-17 09:59 UTC, cedricr commented on package.json
> +    "dayjs": "^1.11.4",
même chose avec uid?

2022-08-17 09:59 UTC, cedricr commented on package.json
> +    "@types/sinonjs__fake-timers": "^8.1.2",
pas compris: on peut l'enlever du package.json ou pas du coup?

2022-08-17 09:59 UTC, cedricr commented on src/lib/utils/service/index.ts
> +type ServiceUpdateStatusData = {
oui oui, mais ça aurait pu être deux fonctions d'affichage differentes. Mais oui, laissons comme ça pour le moment, c'est un détail.

2022-08-17 12:12 UTC, AlexandreCantin commented on package.json
> +    "@types/sinonjs__fake-timers": "^8.1.2",
J'ai oublié de l'enlever en même temps que `fake-timers`
Et j'ai ré-oublié de l'enlever après avoir dit que j'ai oublié de l'enlever 😢

2022-08-17 12:19 UTC, AlexandreCantin commented on package.json
> +    "dayjs": "^1.11.4",
même chose :)

2022-08-17 12:33 UTC, merged